* unreal engine learning
:PROPERTIES:
:CUSTOM_ID: unreal-engine-learning
:END:
[[https://github.com/botman99/ue4-xcode-vscode-mac][ue4-xcode-vscode-mac]]

** GenerateProjectFiles.sh

#+begin_src sh
cd /Users/Shared/Epic\ Games/UE_5.4/Engine/Build/BatchFiles/Mac

./GenerateProjectFiles.sh -project="/Users/gerald/Documents/Unreal Projects/a1/a1.uproject" -game -vscode

#+end_src

copy from [[https://medium.com/techiepedia/setting-up-unreal-engine-m1-macbook-for-c-game-development-eb40c12237d1][Setting up Unreal engine in M1 Mac for C++ game development]]


** using ue4 tool

#+begin_src sh
## pip install ue4cli
pip3 install --break-system-packages ue4cli
## macos
ue4 setroot /Users/Shared/Epic\ Games/UE_5.4
## linux
## ue4 setroot /opt/unreal-engine

# add below into ~/.zshrc
# Expand ue4cli
ue() {
  ue4cli=/usr/local/bin/ue4
  ## linux
  ## ue4cli=~/.local/bin/ue4
  engine_path=$($ue4cli root)

  # cd to ue location
  if [[ "$1" == "engine" ]]; then
    cd $engine_path
    # combine clean and build in one command
  elif [[ "$1" == "rebuild" ]]; then
    $ue4cli clean
    $ue4cli build
    if [[ "$2" == "run" ]]; then
      $ue4cli run
    fi
    # build and optionally run while respecting build flags
  elif [[ "$1" == "build" ]]; then
    if [[ "${@: -1}" == "run" ]]; then
      length="$(($# - 2))" # Get length without last param because of 'run'
      $ue4cli build ${@:2:$length}
      $ue4cli run
    else
      shift 1
      $ue4cli build "$@"
    fi
    # Run project files generation, create a symlink for the compile database and fix-up the compile database
  elif [[ "$1" == "gen" ]]; then
    $ue4cli gen
    project=${PWD##*/}
    cat ".vscode/compileCommands_${project}.json" | python3 -c 'import json,sys
j = json.load(sys.stdin)
for o in j:
  file = o["file"]
  arg = o["arguments"][1]
  o["arguments"] = ["clang++ -std=c++20 -ferror-limit=0 -Wall -Wextra -Wpedantic -Wshadow-all -Wno-unused-parameter \"" + file + "\" \"" + arg + "\""]
print(json.dumps(j, indent=2))' > compile_commands.json
    # Pass through all other commands to ue4
  else
    $ue4cli "$@"
  fi
}

alias ue4='echo Please use ue instead.'
alias ue5='echo Please use ue instead.'
#+end_src

command usage:

#+begin_src sh
ue4 editor

cd /path/to/project
ue4 run

ue4 build

ue4 gen
#+end_src

gen compile_commands.json
#+begin_src sh
# /Users/Shared/Epic\ Games/UE_5.2/Engine/Build/BatchFiles/Mac/GenerateProjectFiles.sh -project="/Users/gerald/Documents/Unreal Projects/a4/a4.uproject" -game -vscode

/usr/local/bin/ue4 gen -vscode

ue gen
#+end_src

copy from [[https://neunerdhausen.de/posts/unreal-engine-5-with-vim/][Unreal Engine 5 with Vim or Emacs on Linux]]
copy from [[https://github.com/adamrehn/ue4cli/issues/18][UnrealBuildTool isn't built by ue4 build]]
also see [[https://docs.adamrehn.com/ue4cli/overview/introduction-to-ue4cli][Introduction to ue4cli]]

** change project directory

#+begin_src sh
vim ~/Library/Preferences/Unreal Engine/EpicGamesLauncher/Mac/GameUserSettings.ini

CreatedProjectPaths=/Users/gerald/Documents/Unreal-Projects
#+end_src

copy from [[https://forums.unrealengine.com/t/how-do-i-get-a-project-to-show-up-in-the-project-browser/515095/2][How do I get a project to show up in the Project Browser]]

** lua plugin

[[https://github.com/Tencent/sluaunreal][sluaunreal]]
[[https://github.com/Tencent/UnLua][UnLua]]


** unreal engine using C++20 Default Version

#+begin_quote
UE 5.3 is now compiled with the latest C++20 standard, and the version is supported in your development environment.


C++20 support has been added to the UnrealBuildTool (UBT) and is controllable with a Target or Module setting; C++14 is marked deprecated and no longer supported.



All engine modules are compiled by default with C++20, regardless of the target C++ standard. Other modules still support C++17 but can be opted-in to C++20 if desired.
#+end_quote

copy from [[https://portal.productboard.com/epicgames/1-unreal-engine-public-roadmap/c/1165-c-20-default-version][C++20 Default Version]]

** compile unreal-engine in archlinux from source

[[https://aur.archlinux.org/packages/unreal-engine-bin][unreal-engine-bin]] 5.4.1 does not work with [[https://github.com/adamrehn/ue4cli][ue4cli]]

#+begin_src shell
yay -S unreal-engine
#+end_src

By running this command line, in _yay install prepare_ period, stop the command line.

Edit _~/.cache/yay/unreal-engine/PKGBUILD_ file

#+begin_src shell
prepare() {
   # ...
  cd "${pkgname}" || return
    CURRENT_CLONED_VERSION="$(git describe --tags)"
    if [ "${CURRENT_CLONED_VERSION}" != "${pkgver}-release" ]; then
      cd ..
      # rm -rf "${pkgname}"
      git clone --depth=1 --branch=${pkgver}-release git@github.com:EpicGames/UnrealEngine "${pkgname}"
      cd "${pkgname}" || return
    else
      rm -f .git/index.lock
      git fetch --depth=1 origin tag ${pkgver}-release
      git reset --hard ${pkgver}-release
#+end_src

_# rm -rf "${pkgname}"_ is commented.

continue to run command:

#+begin_src shell
cd ~/.cache/yay/unreal-engine
updpkgsums
makepkg --holdver

sudo pacman -U unreal-engine-5.4.1-0-x86_64.pkg.tar.zst

sudo groupadd unrealengine-users
sudo usermod -aG unrealengine-users ${USERNAME}
sudo chown -R ${USERNAME}:unrealengine-users /opt/unreal-engine
sudo chmod -R 775 /opt/unreal-engine
#+end_src

see [[https://aur.archlinux.org/packages/unreal-engine][Package Details: unreal-engine]]


** macos install dotnet

#+begin_src shell
brew remove dotnet@6
brew install dotnet
echo 'export DOTNET_ROOT="/usr/local/opt/dotnet/libexec"' >> ~/.zshrc
source ~/.zshrc
#+end_src

After this, unreal-engine does not crash, and works well.