" Setting up Vundle - the vim plugin bundler
let iCanHazVundle=1
let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
if !filereadable(vundle_readme)
	echo "Installing Vundle.."
	echo ""
	silent !mkdir -p ~/.vim/bundle
	silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
	let iCanHazVundle=0
endif
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'jimenezrick/vimerl'
set autoindent
set ignorecase
set tabstop=4
set shiftwidth=4
set nu
set hlsearch
set incsearch
set fencs=utf-8,gbk
set equalalways
syntax on
set list lcs=tab:\|\ 
"set paste
set cursorline
set ruler
set fencs=utf-8,gbk
set incsearch
set laststatus=2
set statusline=\ %<%F[%1*%M%*%n%R%H]%=\ %y\ %0(%{&fileformat}\ %{&encoding}\ %c:%l@%L%)/
set nocompatible
set ignorecase smartcase
set wildmenu
set background=light
set ts=4
set expandtab
"expandtab off

filetype plugin indent on
let g:erlangManPath="/usr/local/otp_src_19.2/lib/erlang/man"
set autoindent
set list
colorscheme desert
set paste
