p* archlinux command
:PROPERTIES:
:CUSTOM_ID: archlinux-command
:END:
** intallation
:PROPERTIES:
:CUSTOM_ID: intallation
:END:
see [[https://zhuanlan.zhihu.com/p/433920079][Archlinux
安装教程超详细（2021.11.15）]]

see
[[https://www.securedyou.com/how-to-install-arch-linux-step-by-step-tutorial/][How
to Install Arch Linux in 2022 {Easy Step-by-Step Guide}]]

see [[https://www.cnblogs.com/LzsCxb/p/15669736.html][Archlinux
2022安装配置之Gnome40]]

#+begin_src shell
# reflector --country China --age 72 --sort rate --protocol https --save /etc/pacman.d/mirrorlist

vim /etc/pacman.d/mirrorlist
-------------------------------
## delete all other mirrors
Server = https://mirrors.163.com/archlinux/$repo/os/$arch

timedatectl set-ntp true

cfdisk /dev/sda


// none efi
mount /dev/sda3 /mnt

// efi option, EFI system partition
mount /dev/nvme0n1p2 /mnt
mkdir /mnt/boot
mount /dev/nvme0n1p1 /mnt/boot

// mount other part disk
mkdir /mnt/backup
mount /dev/sda2 /mnt/backup

pacstrap /mnt linux linux-firmware linux-headers base base-devel vim git \
    net-tools openssh gdm xorg xorg-server xorg-xinit xorg-xrandr \
    gnome gnome-extra gnome-shell grub efibootmgr \
    intel-ucode proxychains v2ray gnome-tweaks pacman-contrib \
    util-linux  wget xf86-video-nouveau xf86-video-intel mesa-libgl \
    wqy-zenhei cmake reflector bc nano zsh trash-cli vlc cpio xmlto python-sphinx_rtd_theme \
    adobe-source-han-serif-cn-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra \
    adobe-source-han-sans-cn-fonts ttf-sarasa-gothic nfs-utils mpv wpa_supplicant \
    gst-libav a52dec faac faad2 flac jasper lame libdca libdv libmad libmpeg2 \
    libtheora libvorbis libxv wavpack x264 xvidcore p7zip tmux \
    fcitx-configtool fcitx fcitx-gtk3 sunpinyin fcitx-sunpinyin gthumb

genfstab -U /mnt >> /mnt/etc/fstab
// after genfstab , if `/mnt/boot` is mounted, check the `/mnt/etc/fstab`
// if the `/mnt/etc/fstab` file  does not contain `/mnt/boot`, it must be installed error.

arch-chroot /mnt

cat >>/etc/pacman.conf <<EOF
[archlinuxcn]
Server = https://mirrors.ustc.edu.cn/archlinuxcn/\$arch
EOF

pacman -Syyu
pacman -S --noconfirm archlinuxcn-keyring

pacman -S --noconfirm virtualbox-ext-oracle gstreamer0.10-base-plugins netease-cloud-music authy vdhcoapp feishu-bin

ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
hwclock --systohc

# locale
sed --in-place=.bak 's/^#en_US\.UTF-8/en_US\.UTF-8/' /etc/locale.gen
sed --in-place=.bak2 's/^#zh_CN\.UTF-8/zh_CN\.UTF-8/' /etc/locale.gen
locale-gen


echo "LANG=zh_CN.UTF-8" > /etc/locale.conf
echo archlinux > /etc/hostname

echo >> /etc/hosts <<EOF
--------------------
127.0.0.1   localhost
::1         localhost
127.0.0.1   archlinux.localdomain archlinux   # 这里的archlinux是主机名
EOF

// optional, check the /boot is installed
mkinitcpio -P

// no efi, grub-install --recheck /dev/<目标磁盘>
grub-install /dev/sda

// efi option
// grub-install --target=x86_64-efi --efi-directory=<EFI 分区挂载点> --bootloader-id=arch_grub --recheck
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=arch_grub --recheck

mkdir /boot/EFI/boot
cp /boot/EFI/arch_grub/grubx64.efi  /boot/EFI/boot/bootx64.efi
grub-mkconfig -o /boot/grub/grub.cfg

// checkout the menuentry
grep menuentry /boot/grub/grub.cfg

vim /etc/default/grub
--------------------
GRUB_TIMEOUT=1
GRUB_CMDLINE_LINUX_DEFAULT="text"
GRUB_CMDLINE_LINUX="noapic"

grub-mkconfig -o /boot/grub/grub.cfg

passwd

useradd --create-home user_name
passwd user_name

usermod -aG wheel,users,storage,power,lp,adm,optical user_name

vim /etc/sudoers
## right under the %wheel ALL=(ALL) NOPASSWD: ALL
$USER  ALL=(ALL) NOPASSWD:ALL


systemctl enable sshd

// static ip
vim /etc/systemd/network/static-enp1s0.network
-------------------
[Match]
Name=enp1s0
[Network]
Address=192.168.1.81/24
Gateway=192.168.1.253
DNS=192.168.253.254
DNS=192.168.1.253


vim /etc/systemd/network/static-enp1s0.link
--------------------------------
[Match]
MACAddress=a8:4b:05:2b:e8:54

[Link]
NamePolicy=
Name=enp1s0

// dhcp
vim /etc/systemd/network/dhcp-enp1s0.network
-------------------
[Match]
Name=enp1s0
[Network]
DHCP=ipv4

rmmod pcspkr
echo "blacklist pcspkr" >> /etc/modprobe.d/blacklist.conf

sed -i 's/\#NAutoVTs=6/NAutoVTs=6/' /etc/systemd/logind.conf

systemctl enable systemd-networkd

systemctl enable systemd-resolved.service

exit

umount /mnt

reboot
#+end_src

** login and enable the network
:PROPERTIES:
:CUSTOM_ID: login-and-enable-the-network
:END:
#+begin_src shell
sudo systemctl enable systemd-networkd

sudo systemctl enable systemd-resolved.service

sudo systemctl start gdm.service
// systemctl enable gdm.service

sudo systemctl set-default graphical
#+end_src

** add user and set group
:PROPERTIES:
:CUSTOM_ID: add-user-and-set-group
:END:
#+begin_src shell
useradd --create-home gerald
passwd gerald

usermod -aG wheel,users,storage,power,lp,adm,optical gerald
#+end_src

** add archlinuxcn
:PROPERTIES:
:CUSTOM_ID: add-archlinuxcn
:END:
#+begin_src shell
vim /etc/pacman.conf
--------------------------------------

[archlinuxcn]
Server = https://mirrors.163.com/archlinux-cn/$arch
#+end_src

** install archlinuxcn-keyring
:PROPERTIES:
:CUSTOM_ID: install-archlinuxcn-keyring
:END:
#+begin_src shell
pacman -Syyu
pacman -S --noconfirm archlinuxcn-keyring
#+end_src

** install yay
:PROPERTIES:
:CUSTOM_ID: install-yay
:END:
#+begin_src shell
pacman -S  --noconfirm yay
#+end_src

** set grub and update grub
:PROPERTIES:
:CUSTOM_ID: set-grub-and-update-grub
:END:
#+begin_src shell
vim /etc/default/grub

grub-mkconfig
#+end_src

** install fbterm
:PROPERTIES:
:CUSTOM_ID: install-fbterm
:END:
#+begin_src shell
yay -S --noconfirm fbterm fbv fcitx-fbterm-git v86d

sudo gpasswd -a $USER video

sudo setcap 'cap_sys_tty_config+ep' /usr/bin/fbterm

sudo chmod u+s /usr/bin/fbterm
sudo pacman -S fbgrab
#+end_src

fbterm usage:

#+begin_src shell
       keyboard:
         CTRL_ALT_E:    exit from FbTerm
         CTRL_ALT_C:    create a new window
         CTRL_ALT_D:    destroy current window
         CTRL_ALT_1:    switch to window 1
         CTRL_ALT_2:    switch to window 2
         CTRL_ALT_3:    switch to window 3
         CTRL_ALT_4:    switch to window 4
         CTRL_ALT_5:    switch to window 5
         CTRL_ALT_6:    switch to window 6
         CTRL_ALT_7:    switch to window 7
         CTRL_ALT_8:    switch to window 8
         CTRL_ALT_9:    switch to window 9
         CTRL_ALT_0:    switch to window 10
         SHIFT_LEFT:    switch to previous window
         SHIFT_RIGHT:   switch to next window
         SHIFT_PAGEUP:    history scroll up
         SHIFT_PAGEDOWN:  history scroll down
         CTRL_ALT_F1:                 switch to encoding of current locale
         CTRL_ALT_F2 to CTRL_ALT_F6:  switch to additional encodings
         CTRL_SPACE:    toggle input method
         CTRL_ALT_K:    kill input method server
#+end_src

copy from
[[http://manpages.ubuntu.com/manpages/bionic/man1/fbterm.1.html][fbterm]]

fbterm start with font size:

#+begin_src shell
fbterm -s 40
#+end_src

** set the mirror and update
:PROPERTIES:
:CUSTOM_ID: set-the-mirror-and-update
:END:
#+begin_src shell
cd /etc/pacman.d/
sudo mv mirrorlist  mirrorlist.bak
echo 'Server = http://mirrors.163.com/archlinux/$repo/os/$arch' | sudo tee  mirrorlist
sudo pacman -Syyu
#+end_src

** vagrant box
:PROPERTIES:
:CUSTOM_ID: vagrant-box
:END:
#+begin_src shell
vagrant init ogarcia/archlinux-x64
vagrant up
#+end_src

** asp compile kernel
:PROPERTIES:
:CUSTOM_ID: asp-compile-kernel
:END:
change the asp git remote url:

#+begin_src shell
$ cat ~/.cache/asp/.git/config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "packages"]
        url = https://github.com/archlinux/svntogit-packages.git
        fetch = +refs/heads/*:refs/remotes/packages/*
[remote "community"]
        url = https://github.com/archlinux/svntogit-community.git
        fetch = +refs/heads/*:refs/remotes/community/*
#+end_src

Change the packages url to be
=https://gitee.com/mirrors_Archlinux/svntogit-packages= change the
community url to be
=https://gitee.com/mirrors_Archlinux/svntogit-community= The new file
should be like this:

#+begin_src shell
$ cat ~/.cache/asp/.git/config

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "packages"]
        url = https://gitee.com/mirrors_Archlinux/svntogit-packages
        fetch = +refs/heads/*:refs/remotes/packages/*
[remote "community"]
        url = https://gitee.com/mirrors_Archlinux/svntogit-community
        fetch = +refs/heads/*:refs/remotes/community/*
#+end_src

see [[https://bugs.archlinux.org/task/67359][FS#67359 - [asp] remotes of
existing ASPROOT are not automatically set to GitHub]]

#+begin_src shell
 $ cd ~/
 $ mkdir build
 $ cd build/
 $ asp update linux
 $ asp export linux

 $ cd linux

 // edit `PKGBUILD` file
 ------------------
 pkgbase=linux-custom

 // change pkgname=("$pkgbase" "$pkgbase-headers" "$pkgbase-docs") to be:
 ------------------------------------------------------------------
 pkgname=("$pkgbase" "$pkgbase-headers")

 // change https://github.com/archlinux/linux to be https://gitee.com/mirrors_Archlinux/linux
 ----------------------------------------------------------------------
url="https://gitee.com/mirrors_Archlinux/linux/commits/$_srctag"
  "$_srcname::git+https://gitee.com/mirrors_Archlinux/linux?signed#tag=$_srctag"


------------------
change  the build() function
build() {
  cd $_srcname
  make all
  make htmldocs
}

to be :
build() {
  cd $_srcname
  make all -j$(nproc)
  make htmldocs
}

## git clone the linux source file into the src directory

``` shell
mkdir src/

git clone https://gitee.com/mirrors_ArchLinux/linux src/archlinux-linux
#+end_src

** then run the updpkgsums command
:PROPERTIES:
:CUSTOM_ID: then-run-the-updpkgsums-command
:END:
#+begin_src shell

 $ mv config config.origin

 $ zcat /proc/config.gz > config

 ## edit `config` file
 ------------------
 CONFIG_SATA_PMP=n

 ## edit `PKGBUILD` file
 ------------------
 pkgbase=linux-custom

 ## change pkgname=("$pkgbase" "$pkgbase-headers" "$pkgbase-docs") to be:
 pkgname=("$pkgbase" "$pkgbase-headers")

 ## ------------------
## change  the build() function
build() {
  cd $_srcname
  make all
  make htmldocs
}

to be :
build() {
  cd $_srcname
  make all -j$(nproc)
  make htmldocs
}


 $ updpkgsums
 # network might be broken, use proxy
 $ proxychains makepkg -s

// clean up
$ cd ~/build/linux/src/archlinux
$ git branch --delete --force --verbose 5.16.11-arch1-1
#+end_src

copy from [[https://wiki.archlinux.org/title/Kernel_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)/Arch_Build_System_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)][Kernel (简体中文)/Arch Build System (简体中文)]]
also see [[https://wiki.archlinux.org/title/Kernel/Arch_Build_System][Kernel/Arch Build System]]
also see [[https://cloud.tencent.com/developer/article/1791129][使用ABS编译ArchLinux内核]]

** git clone source and makepkg
:PROPERTIES:
:CUSTOM_ID: git-clone-source-and-makepkg
:END:
#+begin_src shell

 $ asp update linux
 $ asp export linux
 $ cd linux
 $ git clone https://gitee.com/mirrors_Archlinux/linux archlinux-linux

 // edit `PKGBUILD` file
 ------------------
 pkgbase=linux-custom3
 pkgver=6.5.7.arch1

 // change pkgname=("$pkgbase" "$pkgbase-headers" "$pkgbase-docs") to be:
 ------------------------------------------------------------------
 pkgname=("$pkgbase" "$pkgbase-headers")

 build() {
   cd $_srcname
   _make htmldocs all
}
  to change be:
build() {
   cd $_srcname
   _make all
}

 $ mv config config.origin

 $ zcat /proc/config.gz > config

 ## edit `config` file
 ------------------
 CONFIG_SATA_PMP=n

 $ cd archlinux-linux
 // checkout a tag like 6.5.7-arch1
 // $ git branch --delete --force --verbose 6.5.7-arch1
 $ git checkout tags/v5.16.11-arch1 -b 6.5.7-arch1
 $ cd ..

 $ rm -rf pkg src  ## there might be old building directory
 $ updpkgsums
 $ makepkg --holdver
 $ sudo pacman -U <kernel-headers_package>
 $ sudo pacman -U <kernel_package>
 $ sudo grub-mkconfig -o /boot/grub/grub.cfg

 # and run as USER:
 yay -S nvidia-390xx-dkms
 yay -S nvidia-340xx-dkms

 sudo cp /usr/share/nvidia-340xx/20-nvidia.conf /etc/X11/xorg.conf.d/

 // uninstall custom linux kernel
 $ sudo pacman -R linux-custom-headers
 $ sudo pacman -R linux-custom
 $ sudo grub-mkconfig -o /boot/grub/grub.cfg
#+end_src

copy from [[https://unix.stackexchange.com/questions/154919/how-to-modify-a-pkgbuild-which-uses-git-sources-to-pull-only-a-shallow-clone][How to modify a PKGBUILD which uses git sources to pull only a shallow clone?]]

** fix Verifying source file signatures with gpg
#+begin_quote
Verifying source file signatures with gpg...
    archlinux-linux git repo ... SIGNATURE NOT FOUND
==> ERROR: One or more PGP signatures could not be verified!
#+end_quote

It must fetch the latest source, including tags
#+begin_src shell
cd archlinux-linux
git fetch origin --tags
git checkout master
git reset --hard origin/master
#+end_src

** install software
:PROPERTIES:
:CUSTOM_ID: install-software
:END:
#+begin_src shell
sudo pacman -S proxychains vim v2ray
#+end_src

** archlinux-linux git repo ... FAILED (unknown public key 3B94A80E50A477C7)
:PROPERTIES:
:CUSTOM_ID: archlinux-linux-git-repo-failed-unknown-public-key-3b94a80e50a477c7
:END:
#+begin_src shell
gpg --keyserver hkps://keys.openpgp.org  --recv-keys 3B94A80E50A477C7

// or
wget -c https://keys.openpgp.org/vks/v1/by-fingerprint/A2FF3A36AAA56654109064AB19802F8B0D70FC30 https://keys.openpgp.org/vks/v1/by-fingerprint/C7E7849466FE2358343588377258734B41C31549
gpg --import A2FF3A36AAA56654109064AB19802F8B0D70FC30
gpg --import C7E7849466FE2358343588377258734B41C31549
#+end_src

copy from [[https://bbs.archlinux.org/viewtopic.php?id=268750][[SOLVED] Unknown public key error while building linux kernel]]

** install gnome desktop
:PROPERTIES:
:CUSTOM_ID: install-gnome-desktop
:END:
#+begin_src shell
sudo pacman -S xorg-server xorg-xinit gnome gnome-extra
#+end_src

copy from
[[https://starrycat.me/archlinux-install-gnome-desktop.html][ArchLinux安装GNOME图形桌面环境]]

** install via ssh remotely
:PROPERTIES:
:CUSTOM_ID: install-via-ssh-remotely
:END:
#+begin_src shell
reflector --country China --age 72 --sort rate --protocol https --save /etc/pacman.d/mirrorlist

sudo pacman -Syy

## add password of root user
passwd

sudo pacman -S net-tools openssh glibc

systemctl start sshd

sudo pacman -S archinstall
#+end_src

copy from [通过ssh远程安装arch linux
](https://blog.51cto.com/u_3258791/2097197）

** systemd-analyze
:PROPERTIES:
:CUSTOM_ID: systemd-analyze
:END:
#+begin_src shell
systemd-analyze blame
systemd-analyze critical-chain
systemd-analyze plot > plot.svg
#+end_src

see [[https://wiki.archlinux.org/title/Improving_performance/Boot_process][Improving performance/Boot process]]

also see [[https://forum.manjaro.org/t/manjaro-booting-is-very-slow-40sec/32489][Manjaro booting is very slow (40sec)]]

** yay usage
:PROPERTIES:
:CUSTOM_ID: yay-usage
:END:
#+begin_src shell
# Instalk dkms :
sudo pacman -Sy dkms

# Install Yay :
sudo pacman -Sy yay

# and run as USER:
yay -S nvidia-390xx-dkms
yay -S nvidia-340xx-dkms

sudo cp /usr/share/nvidia-340xx/20-nvidia.conf /etc/X11/xorg.conf.d/
#+end_src

copy from [[https://www.reddit.com/r/archlinux/comments/g4e6qq/unable_to_find_nvidia390xx_anymore/][Unable to find =nvidia-390xx= anymore]]
also see [[https://wiki.archlinux.org/title/NVIDIA#Unsupported_drivers][Unsupported_drivers]]

** nvidia
:PROPERTIES:
:CUSTOM_ID: nvidia
:END:
#+begin_src shell
sudo pacman -S viadia
#+end_src

For the Maxwell (NV110/GMXXX) series and newer, install the nvidia
package copy from [[https://wiki.archlinux.org/title/NVIDIA][NVIDIA]]

GeForce 930起、10系至20系、 Quadro/Tesla/Tegra
K-系列以及更新的显卡（NV110以及更新的显卡家族），安装 nvidia
（用于linux） 或者 nvidia-lts （用于linux-lts）。 copy from
[[https://wiki.archlinux.org/title/NVIDIA_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)][NVIDIA
(简体中文)]]

** install typora
:PROPERTIES:
:CUSTOM_ID: install-typora
:END:
#+begin_src shell
sudo pacman -S typora
#+end_src

** install virtualbox
:PROPERTIES:
:CUSTOM_ID: install-virtualbox
:END:
#+begin_src shell
sudo pacman -S virtualbox virtualbox-host-dkms virtualbox-guest-iso \
    virtualbox-ext-oracle

sudo gpasswd -a $USER vboxusers

sudo systemctl enable --now vboxweb.service

echo -e "vboxdrv\nvboxnetflt\nvboxnetadp\nvboxpci" | sudo tee -a /etc/modules-load.d/virtualbox.conf

sudo vboxreload

// or setup
sudo /sbin/rcvboxdrv setup
#+end_src

copy from [[https://cxybb.com/article/weixin_34280237/91997886][Arch Linux 安装 virtualbox_powerx_yc的博客-程序员宝宝]]

** chinese font
:PROPERTIES:
:CUSTOM_ID: chinese-font
:END:
#+begin_src shell
sudo pacman -S wqy-zenhei adobe-source-han-serif-cn-fonts

sudo pacman -S noto-fonts-cjk noto-fonts-emoji noto-fonts-extra adobe-source-han-sans-cn-fonts adobe-source-han-serif-cn-fonts  ttf-sarasa-gothic
#+end_src

** install nfs-utils
:PROPERTIES:
:CUSTOM_ID: install-nfs-utils
:END:
#+begin_src shell
sudo pacman -S nfs-utils
#+end_src

** stop packagekit.service
:PROPERTIES:
:CUSTOM_ID: stop-packagekit.service
:END:
#+begin_src shell
sudo systemctl stop packagekit.service
#+end_src

copy from [[https://bbs.archlinux.org/viewtopic.php?pid=1975599#p1975599][Gnome software store stopped working]]

** install google-chrome browser
:PROPERTIES:
:CUSTOM_ID: install-google-chrome-browser
:END:
#+begin_src shell
yay -S google-chrome
#+end_src

** pacman-key
:PROPERTIES:
:CUSTOM_ID: pacman-key
:END:
#+begin_src shell
mv /etc/pacman.d/gnupg /etc/pacman.d/gnupg.bak

pacman-key --init
pacman-key --populate archlinux
sudo pacman -Syyu
#+end_src

** pam fails to find unit dbus-org.freedesktop.home1.service
:PROPERTIES:
:CUSTOM_ID: pam-fails-to-find-unit-dbus-org.freedesktop.home1.service
:END:
add this to /etc/pacman.conf

#+begin_src shell
NoExtract=usr/lib/security/pam_systemd_home.so
#+end_src

then reinstall systemd

#+begin_src shell
sudo pacman -S systemd
#+end_src

copy from [[https://bbs.archlinux.org/viewtopic.php?pid=1927195#p1927195][pam fails to find unit dbus-org.freedesktop.home1.service]]

** mpv player
:PROPERTIES:
:CUSTOM_ID: mpv-player
:END:
#+begin_src shell
sudo pacman -S mpv
#+end_src

copy from
[[https://www.reddit.com/r/archlinux/comments/blo3zs/vlc_process_remains_active_after_closing_it/][VLC -
process remains active after closing it]]

** ugreen ac1300 wireless card
:PROPERTIES:
:CUSTOM_ID: ugrren-ac1300-wireless-card
:END:
#+begin_src shell
git clone https://github.com/morrownr/8812au-20210820
cd 8812au-20210820
sudo ./install-driver.sh
sudo reboot
#+end_src

copy from
[[https://aur.archlinux.org/packages/rtl88xxau-aircrack-dkms-git][Package Details: rtl88xxau-aircrack-dkms-git r1174.3a6402e-1]]

** delete and update driver
#+begin_src shell
sudo sh remove-driver.sh
sudo dkms remove rtl8812au/5.13.6 --all
sudo sh install-driver.sh
#+end_src

** some useful command:
:PROPERTIES:
:CUSTOM_ID: some-useful-command
:END:
#+begin_src shell
lspci -k // 检查驱动状态
ip link
iw dev // 以上三种方法都能列出网卡接口名称，如果未列出，说明驱动有问题。

dmesg | grep firmware
dmesg | grep iwlwifi // 这两种方法是在驱动有问题时，可以用来检查和寻找问题。

iw dev wlp3s0 link // 用来检查网卡是否连接，其中 wlp3s0 是网卡接口名称

ip link set dev wlp3s0 up // 用来将无线网卡接口启用

iw dev wlp3s0 scan // 用来扫描周围的无线热点

iw dev wlp3s0 connect "your_essid" // 此命令可以直接连接没有加密的热点
iw dev wlp3s0 connect "your_essid" key 0:your_key // 用来连接WEP加密的热点

wpa_supplicant -D nl80211,wext -B -i wlp3s0 -c /etc/wpa_supplicant/wpa_supplicant.conf
// 这是 wpa_supplicant 连接WPA/WPA2的命令格式

dhcpcd wlp3s0 // 给无线网卡分配动态IP
#+end_src

copy from [[https://wangbinweb.github.io/htm/18-archlinux-install-wireless-network-card.htm][archlinux 系统安装无线网卡]]
also see [[https://wiki.archlinux.org/title/Network_configuration_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)/Wireless_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)][Network configuration (简体中文)/Wireless (简体中文)]]

** ctrl swap caps
:PROPERTIES:
:CUSTOM_ID: ctrl-swap-caps
:END:
Get the option:

#+begin_src shell
grep "caps" /usr/share/X11/xkb/rules/xorg.lst
#+end_src

add following line to ~/.xinitrc or ~/.xsession, before the exec
gnome-session (or similar) line .

#+begin_src shell
setxkbmap -option ctrl:swapcaps
#+end_src

copy from [[https://n1ghtmare.github.io/2021-05-19/remapping-caps-lock-to-esc-on-arch-linux/][Remapping Caps Lock to Esc on Arch Linux]]
also see [[https://itectec.com/superuser/how-to-map-the-caps-lock-key-to-escape-key-in-arch-linux/][Linux -- How to map the Caps Lock key to Escape key in Arch Linux]]

** samba
:PROPERTIES:
:CUSTOM_ID: samba
:END:
#+begin_src shell
sudo pacman -S samba

sudo vim /etc/samba/smb.conf
# ----------------------------- 　　添加以下内容
[global]
    dns proxy = No
    map to guest = Bad User
    netbios name = ARCH LINUX
    security = USER
    server string = Samba Server %v
    idmap config * : backend = tdb


[public]
    guest ok = Yes
    path = /home/test/shares
    read only = Yes


[private]
    path = /home/test/privates
    read only = Yes
    write list = @test

#--------------------------------

sudo mkdir /home/test
sudo mkdir /home/test/shares

sudo mkdir /home/test/privates

sudo chmod 777 /home/test/shares

sudo chmod 777 /home/test/privates

sudo groupadd smbgroup

sudo useradd -g smbgroup test

sudo smbpasswd -a test


sudo vim /etc/ssh/sshd_config
------------------------
AllowUsers  root@192.168.1.1 valid_user  # no test user here, test user is not allowed to login

sudo usermod --shell /usr/bin/nologin --lock test


sudo systemctl start smb
sudo systemctl enable smb

sudo systemctl restart sshd
#+end_src

see [[https://www.cnblogs.com/chenyucong/p/8452770.html][Arch Linux下配置Samba]]
see [[https://wiki.archlinux.org/title/Samba_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)][Samba (简体中文)]]
see [[https://www.xiebruce.top/1089.html][Linux -- 限制ssh的登录用户和登录ip]]

** mount external disk drivers
:PROPERTIES:
:CUSTOM_ID: mount-external-disk-drivers
:END:
in the =/etc/fstab=

#+begin_src shell
UUID=177ce77f-6e06-47a6-b1e9-6c3a6b43fb8d /run/media/sinux/sinux3       ext4    noatime,x-systemd.mount-timeout=5min,x-systemd.automount,x-systemd.device-timeout=10,x-systemd.idle-timeout=1min 0 2
// or
UUID=XXXXXXXXXXXXXXX  /myfs btrfs defaults,auto,nofail,x-systemd.device-timeout=30,x-systemd.mount-timeout=30 0 0
#+end_src

A couple things:

1 You are missing a 2 at the end of the line for sinux3 2 You should use
systemd-automounts to mount external drives. That way it doesn't matter
if they are connected or not. It won't impact your boot and you won't
have manually mount them later. copy from
[[https://forum.endeavouros.com/t/dependency-failed-for-file-system-check-external-drives/16249][Dependency
failed for File System Check External Drives]] copy from
[[https://askubuntu.com/questions/14365/mount-an-external-drive-at-boot-time-only-if-it-is-plugged-in][Mount
an external drive at boot time only if it is plugged in]]

** grub acpi
:PROPERTIES:
:CUSTOM_ID: grub-acpi
:END:
#+begin_src shell
GRUB_CMDLINE_LINUX="noapic acpi=off"
GRUB_CMDLINE_LINUX_DEFAULT="i8042.nomux=1 i8042.reset"

// or
GRUB_CMDLINE_LINUX_DEFAULT="i8042.nomux=1"

// or
GRUB_CMDLINE_LINUX_DEFAULT="i8042.reset i8042.nomux i8042.nopnp i8042.noloop"
#+end_src

see
[[https://unix.stackexchange.com/questions/28736/what-does-the-i8042-nomux-1-kernel-option-do-during-booting-of-ubuntu][What
does the 'i8042.nomux=1' kernel option do during booting of Ubuntu?]]
also see [[https://forums.linuxmint.com/viewtopic.php?t=356420][Keyboard
issue on Asus UM425UAZ]] also see
[[https://askubuntu.com/questions/929904/cant-pass-the-acpi-off-problem][Can't
pass the acpi=off problem]]

** ntp
:PROPERTIES:
:CUSTOM_ID: ntp
:END:
#+begin_src shell
sudo pacman -S ntp

sudo ntpdate pool.ntp.org
sudo hwclock -w

sudo timedatectl set-ntp true
#+end_src

also see
[[https://wiki.archlinux.org/title/Systemd-timesyncd_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)][systemd-timesyncd
(简体中文)]]

** Disable the grub sub-menu
:PROPERTIES:
:CUSTOM_ID: disable-the-grub-sub-menu
:END:
edit the file =/etc/default/grub=

#+begin_src shell
GRUB_DEFAULT=saved
GRUB_SAVEDEFAULT=true
GRUB_DISABLE_SUBMENU=y
#+end_src

Then run the command:

#+begin_src shell
sudo grub-mkconfig -o /boot/grub/grub.cfg
#+end_src

** clean archlinux
:PROPERTIES:
:CUSTOM_ID: clean-archlinux
:END:
#+begin_src shell
// Clean package cache
sudo pacman -Sc
sudo pacman -Scc
sudo pacman -S pacman-contrib

sudo vim /etc/systemd/system/paccache.timer
-----------------------------
[Unit]
Description=Clean-up old pacman pkg

[Timer]
OnCalendar=monthly
Persistent=true

[Install]
WantedBy=multi-user.target
-----------------------------

sudo systemctl enable paccache.timer
sudo systemctl start paccache.timer


//  Remove unused packages (orphans)
sudo pacman -Qtdq
sudo pacman -Rns $(pacman -Qtdq)


// Remove duplicates, empty files, empty directories and broken symlinks
sudo pacman -S rmlint
rmlint /home/alu
#+end_src

copy from [[https://averagelinuxuser.com/clean-arch-linux/][How to clean
Arch Linux]]

** delete linux kernel
:PROPERTIES:
:CUSTOM_ID: delete-linux-kernel
:END:
The -s flag will remove unused linux dependencies as well.

#+begin_src shell
sudo pacman -Ss linux
sudo pacman -Rs linux
#+end_src

copy from
[[https://www.reddit.com/r/archlinux/comments/mnbv18/can_i_get_rid_off_unused_linux_kernels/][Can
I get rid off unused linux kernels?]]

** Set default kernel in GRUB using grub-set-default command line
:PROPERTIES:
:CUSTOM_ID: set-default-kernel-in-grub-using-grub-set-default-command-line
:END:
#+begin_src shell
grep menuentry /boot/grub/grub.cfg
#+end_src

You'll see each kernel listed with the name that is shown in the GRUB
boot menu. The first one is 0, the second is 1, and so on.

#+begin_src shell
sudo grub-set-default X
#+end_src

where X is the number of the kernel you want to boot into.

Also set the X in the =/etc/default/grub= file

#+begin_src shell
GRUB_DEFAULT=X
#+end_src

and then running

#+begin_src shell
sudo grub-mkconfig -o /boot/grub/grub.cfg

// in some distribution
sudo update-grubas
#+end_src

copy from
[[https://unix.stackexchange.com/questions/198003/set-default-kernel-in-grub][Set
default kernel in GRUB]]

** Set default kernel in GRUB manually
:PROPERTIES:
:CUSTOM_ID: set-default-kernel-in-grub-manually
:END:
1) Find the $menuentry_id_option for the submenu:

#+begin_src shell
$ grep submenu /boot/grub/grub.cfg
submenu 'Advanced options for Debian GNU/Linux' $menuentry_id_option 'gnulinux-advanced-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
#+end_src

2) [@2] Find the $menuentry_id_option for the menu entry for the kernel
   you want to use:

#+begin_src shell
$ grep gnulinux /boot/grub/grub.cfg
menuentry 'Debian GNU/Linux' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
submenu 'Advanced options for Debian GNU/Linux' $menuentry_id_option 'gnulinux-advanced-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
    menuentry 'Debian GNU/Linux, with Linux 4.18.0-0.bpo.1-rt-amd64' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.18.0-0.bpo.1-rt-amd64-advanced-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
    menuentry 'Debian GNU/Linux, with Linux 4.18.0-0.bpo.1-rt-amd64 (recovery mode)' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.18.0-0.bpo.1-rt-amd64-recovery-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
    menuentry 'Debian GNU/Linux, with Linux 4.18.0-0.bpo.1-amd64' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.18.0-0.bpo.1-amd64-advanced-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
    menuentry 'Debian GNU/Linux, with Linux 4.18.0-0.bpo.1-amd64 (recovery mode)' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.18.0-0.bpo.1-amd64-recovery-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
    menuentry 'Debian GNU/Linux, with Linux 4.17.0-0.bpo.1-amd64' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.17.0-0.bpo.1-amd64-advanced-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
    menuentry 'Debian GNU/Linux, with Linux 4.17.0-0.bpo.1-amd64 (recovery mode)' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.17.0-0.bpo.1-amd64-recovery-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
    menuentry 'Debian GNU/Linux, with Linux 4.9.0-8-amd64' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.9.0-8-amd64-advanced-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
    menuentry 'Debian GNU/Linux, with Linux 4.9.0-8-amd64 (recovery mode)' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-4.9.0-8-amd64-recovery-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc' {
#+end_src

3) [@3] Comment out your current default grub in /etc/default/grub and
   replace it with the sub-menu's $menuentry_id_option from step one,
   and the selected kernel's $menuentry_id_option from step two
   separated by >.

In my case the modified GRUB_DEFAULT is:

#+begin_src shell
#GRUB_DEFAULT=0

GRUB_DEFAULT="gnulinux-advanced-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc>gnulinux-4.18.0-0.bpo.1-amd64-advanced-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc"
#+end_src

4) [@4] Update grub to make the changes. For Debian this is done like
   so:

#+begin_src shell
$ sudo update-grub

$ sudo grub-mkconfig -o /boot/grub/grub.cfg
#+end_src

5) [@5] Changing this back to the most recent kernel is as simple as
   commenting out the new line and uncommenting #GRUB_DEFAULT=0:

#+begin_src shell
GRUB_DEFAULT=0

#GRUB_DEFAULT="gnulinux-advanced-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc>gnulinux-4.18.0-0.bpo.1-amd64-advanced-38ea4a12-6cfe-4ed9-a8b5-036295e62ffc"
#+end_src

then rerunning update-grub.

copy from
[[https://unix.stackexchange.com/questions/198003/set-default-kernel-in-grub][Set
default kernel in GRUB]] also see
[[http://www.humans-enabled.com/2014/08/how-to-set-default-grub-kernel-boot.html][How
To Set Default Grub / kernel / boot option on Ubuntu GNU/Linux 14.04]]

** kde
:PROPERTIES:
:CUSTOM_ID: kde
:END:
#+begin_src shell
sudo pacman -S plasma kde-applications
#+end_src

** install i3 desktop
:PROPERTIES:
:CUSTOM_ID: install-i3-desktop
:END:
#+begin_src shell
sudo pacman -S i3-gaps i3blocks i3lock i3status

sudo pacman -S lightdm lightdm-gtk-greeter
sudo systemctl enable lightdm

sudo pacman -S alacritty
#+end_src

copy from [[https://zhuanlan.zhihu.com/p/384715418][Arch Linux - 安装X
Window和i3]]

** xfce
:PROPERTIES:
:CUSTOM_ID: xfce
:END:
#+begin_src shell
sudo pacman -S xfce4 xfce4-goodies
#+end_src

copy from
[[https://linoxide.com/install-xfce-desktop-on-arch-linux/][Install XFCE
Desktop on Arch Linux]]

also see
[[https://blog.csdn.net/kingolie/article/details/76723448][Archlinux安装xfce4桌面及美化流程]]

** install firefox, google-chrome, tmux
:PROPERTIES:
:CUSTOM_ID: install-firefox-google-chrome-tmux
:END:
#+begin_src shell
sudo pacman -S firefox tmux
yay -S google-chrome
#+end_src

** linux-lts
:PROPERTIES:
:CUSTOM_ID: linux-lts
:END:
`=shell sudo pacman -S linux-lts-headers linux-lts linux-lts-docs=

** efi installation
:PROPERTIES:
:CUSTOM_ID: efi-installation
:END:
#+begin_src shell

parted /dev/nvme0n1
   mklabel gpt
   mkpart primary 4096s 512M
   mkpart primary 512M  100%
   set 1 boot on
   q

mkfs.vfat -F32 /dev/nvme0n1p1
mkfs.btrfs -f /dev/nvme0n1p2


parted /dev/sda
   mklabel gpt
   mkpart primary 4096s 100%
   q


mkfs.btrfs -f /dev/sda2

// grub-install --target=x86_64-efi --efi-directory=<EFI 分区挂载点> --bootloader-id=arch_grub --recheck
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=arch_grub --recheck

mkdir /boot/EFI/boot
cp boot/EFI/arch_grub/grubx64.efi  /boot/EFI/boot/bootx64.efi
grub-mkconfig -o /boot/grub/grub.cfg
#+end_src

copy from
[[https://bbs.archlinuxcn.org/viewtopic.php?id=2895][安装archlinux
后，在grub没报错情况下，重启没有grub启动项目]] also see
[[https://wiki.archlinux.org/title/Installation_guide#GRUB_2][Installation
guide]]

** normal disk partition
:PROPERTIES:
:CUSTOM_ID: normal-disk-partition
:END:
#+begin_src shell
parted /dev/sda
set 1 boot off
set 1 bios_grub on
q
#+end_src

copy from
[[https://superuser.com/questions/903112/grub2-install-this-gpt-partition-label-contains-no-bios-boot-partition][grub2-install:
"this GPT partition label contains no BIOS Boot Partition"]]

** fix fireware warning
:PROPERTIES:
:CUSTOM_ID: fix-fireware-warning
:END:
firmware warning

#+begin_example
==> WARNING: Possibly missing firmware for module: aic94xx
==> WARNING: Possibly missing firmware for module: bfa
==> WARNING: Possibly missing firmware for module: qed
==> WARNING: Possibly missing firmware for module: qla1280
==> WARNING: Possibly missing firmware for module: qla2xxx
==> WARNING: Possibly missing firmware for module: wd719x
==> WARNING: Possibly missing firmware for module: xhci_pci
#+end_example

just run the following command:

#+begin_src shell
yay -S wd719x-firmware aic94xx-firmware upd72020x-fw linux-firmware-qlogic
sudo mkinitcpio -p linux
#+end_src

see [[https://zhuanlan.zhihu.com/p/340918736][Arch Linux
更新出现模块固件缺失的警告]] see
[[https://forum.endeavouros.com/t/warning-about-missing-new-firmware-modules/23052][Warning
about missing "new" firmware modules]]

If install some firmware with network error, say upd72020x-fw, you can
solve by this:

#+begin_src shell
cd ~/.cache/yay/upd72020x-fw
// see the download link
cat PKGBUILD

// for example, wget the pkg
proxychains wget -c https://raw.githubusercontent.com/denisandroid/uPD72020x-Firmware/master/UPDATE.mem
proxychains wget -c https://raw.githubusercontent.com/denisandroid/uPD72020x-Firmware/master/License.rtf
#+end_src

** enable multilib
:PROPERTIES:
:CUSTOM_ID: enable-multilib
:END:
#+begin_src shell
sudo vim /etc/pacman.conf
#+end_src

add the following into the file:

#+begin_src shell
[multilib]
Include = /etc/pacman.d/mirrorlist
#+end_src

Upgrade your system:

#+begin_src shell
sudo pacman -Syyu
#+end_src

Show 32-bit packages in the multilib repository:

#+begin_src shell
pacman -Sl | grep -i lib32
#+end_src

copy from
[[https://low-orbit.net/arch-linux-how-to-enable-multilib][Arch Linux
How to Enable Multilib]]

** swap ctrl and caps
:PROPERTIES:
:CUSTOM_ID: swap-ctrl-and-caps
:END:
#+begin_src shell
sudo mkdir -p /usr/local/share/kbd/keymaps
sudo cp /usr/share/kbd/keymaps/i386/qwerty/us.map.gz /usr/local/share/kbd/keymaps/modified.us.map.gz
#+end_src

Change every occurency of Escape to Caps_Lock and every occurency of
Caps_Lock to Escape in the copied file and rename it to something like
us.map.gz

#+begin_src shell
keycode  29 = Caps_Lock
keycode  58 = Control
#+end_src

set the config:

#+begin_src shell
sudo vim  /etc/vconsole.conf
------------------------------------------
KEYMAP="/usr/local/share/kbd/keymaps/modified.us.map.gz"
#+end_src

reboot

copy from
[[https://unix.stackexchange.com/questions/616290/how-to-swap-escape-and-caps-lock-for-tty-and-x11][Step
by step solution]]

** using loadkeys swap ctrl and caps
:PROPERTIES:
:CUSTOM_ID: using-loadkeys-swap-ctrl-and-caps
:END:
swap-caps-ctrl.map

#+begin_src shell
keymaps 0-255
keycode 58 = Control #This makes Caps act as Ctrl
keycode 29 = Caps_Lock #This makes Ctrl act as Caps
alt_is_meta #This fixes the Alt key



# Then run loadkeys on that file:
# $ sudo loadkeys swap-caps-ctrl.map
# To revert, run:
# $ sudo loadkeys -d #load default keymap file
#+end_src

run it :

#+begin_src shell
sudo loadkeys swap-caps-ctrl.map
#+end_src

get the keyboard map:

#+begin_src shell
dumpkeys > map
#+end_src

copy from
[[https://cxymm.net/article/sheismylife/51069348][终端模式下交换caps和ctrl键]]

** system-timer and service
:PROPERTIES:
:CUSTOM_ID: system-timer-and-service
:END:
see [[https://www.jianshu.com/p/4d457985b831][使用Systemd配置定时任务]]
alas see
[[http://www.ruanyifeng.com/blog/2018/03/systemd-timer.html][Systemd
定时器教程]]

** cannot shutdown customized kernel
:PROPERTIES:
:CUSTOM_ID: cannot-shutdown-customized-kernel
:END:
#+begin_src shell
cat /proc/sys/kernel/printk

echo "7 4 7 4" > /proc/sys/kernel/printk

awk -F: '/:/{print $1}' /proc/net/dev | xargs -i ip link set dev '{}' down
#+end_src

see
[[https://blog.csdn.net/Longyu_wlz/article/details/112122328][工作问题案例：设备关机变重启]]
It might because while shutdowning the linux, the network devices are
still working. So set the network device down before shutdowning the
computer.

** Systemd Filtering output
:PROPERTIES:
:CUSTOM_ID: systemd-filtering-output
:END:
#+begin_src shell
// Show all messages from this boot:
# journalctl -b

// Include explanations of log messages from the message catalog where available
# journalctl -x

// Show all messages from date (and optional time)
# journalctl --since="2012-10-30 18:17:16"

// Show all messages since 20 minutes ago
# journalctl --since "20 min ago"

// Follow new messages
# journalctl -f

// Show all messages by a specific executable:
# journalctl /usr/lib/systemd/systemd

// Show all messages by a specific process
# journalctl _PID=1

// Show all messages by a specific unit
# journalctl -u man-db.service

// Show all messages from user services by a specific unit
$ journalctl --user -u dbus

// Show kernel ring buffer
# journalctl -k

// Show only error, critical and alert priority messages
# journalctl -p err..alert

// Show auth.log equivalent by filtering on syslog facility
# journalctl SYSLOG_FACILITY=10

// It can be sped up significantly by using --file option to force journalctl to look only into most recent journal
# journalctl --file /var/log/journal/*/system.journal -f
#+end_src

copy from
[[https://wiki.archlinux.org/title/Systemd/Journal#Filtering_output][Systemd]]

** update system gpg
:PROPERTIES:
:CUSTOM_ID: update-system-gpg
:END:
#+begin_src shell
sudo rm -fr /etc/pacman.d/gnupg
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -S archlinux-keyring
sudo pacman-key --refresh-keys
sudo pacman -Syyu
#+end_src

copy from
[[https://archived.forum.manjaro.org/t/upgrade-fails-for-one-missing-key/154988][upgrade
FAILS for one missing key]]

** timeshift
:PROPERTIES:
:CUSTOM_ID: timeshift
:END:
#+begin_src shell
sudo pacman -S timeshift

sudo timeshift --list
sudo timeshift --snapshot-device /dev/sdb4
sudo timeshift --restore --snapshot '2019-07-16_16-35-42' --skip-grub

// --tags D stands for Daily Backup
// --tags W stands for Weekly Backup
// --tags M stands for Monthly Backup
// --tags O stands for On-demand Backup
sudo timeshift --create --comments "A new backup" --tags D

sudo timeshift --restore

// more usage on timeshift
timeshift --help
#+end_src

copy from [[https://blog.tiantian.cool/arch-1/][Archlinux 优化之一]]

** makepkg optimization
:PROPERTIES:
:CUSTOM_ID: makepkg-optimization
:END:
#+begin_src shell
vim ~/.makepkg.conf
# -------------------------------------------
CFLAGS="-march=native -O2 -pipe -fno-plt"
CXXFLAGS="-march=native -O2 -pipe -fno-plt"

MAKEFLAGS="-j$(nproc)"

BUILDENV=(!distcc color ccache !check !sign)
BUILDDIR=/tmp/makepkg

COMPRESSXZ=(xz -c -z - --threads=0)
#+end_src

copy from [[https://blog.tiantian.cool/arch-1/][Archlinux 优化之一]]

** podman
:PROPERTIES:
:CUSTOM_ID: podman
:END:
#+begin_src shell
sudo pacman -S podman

echo "$USER:110000:65536" | sudo tee -a  /etc/subuid
echo "$USER:110000:65536" | sudo tee -a  /etc/subgid

podman system migrate

mkdir -p $HOME/.config/containers/
echo -e "[registries.search]\nregistries = ['docker.io']" | tee $HOME/.config/containers/registries.conf
#+end_src

podman usage is just the same with docker. docker is no more needed.

** fuse-overlayfs
:PROPERTIES:
:CUSTOM_ID: fuse-overlayfs
:END:
#+begin_src shell
sudo pacman -S fuse-overlayfs

podman --storage-opt mount_program=/usr/bin/fuse-overlayfs --storage-opt ignore_chown_errors=true run [...]
#+end_src

copy from
[[https://unix.stackexchange.com/questions/689181/error-kernel-does-not-support-overlay-fs-overlay-is-not-supported-over-extfs][Error:
kernel does not support overlay fs: 'overlay' is not supported over
extfs]]

** libvoikko
:PROPERTIES:
:CUSTOM_ID: libvoikko
:END:
#+begin_src shell
sudo pacman -S libvoikko
#+end_src

** genymotion -- android emulator
:PROPERTIES:
:CUSTOM_ID: genymotion-android-emulator
:END:
#+begin_src shell
sudo pacman -S genymotion
#+end_src

** xdroid-bin -- android emulator
:PROPERTIES:
:CUSTOM_ID: xdroid-bin-android-emulator
:END:
#+begin_src shell
yay -S xdroid-bin
#+end_src

** libpam-google-authenticator
:PROPERTIES:
:CUSTOM_ID: libpam-google-authenticator
:END:
#+begin_src shell
sudo pacman -S libpam-google-authenticator
#+end_src

copy from
[[http://blog.lujun9972.win/blog/2020/08/15/%E4%B8%BAlinux%E7%B3%BB%E7%BB%9F%E5%BC%80%E5%90%AF%E5%A4%9A%E5%9B%A0%E7%B4%A0%E8%AE%A4%E8%AF%81/index.html][为Linux系统开启多因素认证]]

** ata1: softreset failed (device not ready)
:PROPERTIES:
:CUSTOM_ID: ata1-softreset-failed-device-not-ready
:END:
kernel option

#+begin_src shell
libata.force=norst
#+end_src

copy from
[[https://www.linuxquestions.org/questions/linux-newbie-8/config_sata_pmp%3Dn-hw-bug-live-arch-debian-mint-does-not-work-4175549085/][CONFIG_SATA_PMP=n,
HW bug, Live Arch Debian Mint does not work.]]

** GDM ignores Wayland and uses X.Org by default
:PROPERTIES:
:CUSTOM_ID: gdm-ignores-wayland-and-uses-x.org-by-default
:END:
#+begin_src shell
/etc/mkinitcpio.conf
MODULES=(nvidia)
#+end_src

copy from
[[https://wiki.archlinux.org/title/GDM#GDM_ignores_Wayland_and_uses_X.Org_by_default][GDM
ignores Wayland and uses X.Org by default]] also see
[[https://wiki.archlinux.org/title/Kernel_mode_setting#Early_KMS_start][Kernel
mode setting]]

** sysrq
:PROPERTIES:
:CUSTOM_ID: sysrq
:END:
see
[[http://blog.lujun9972.win/blog/2018/08/22/linux%E4%B8%8B%E7%9A%84sysrq%E9%94%AE/index.html][linux下的SysRq键]]

** get syslog
:PROPERTIES:
:CUSTOM_ID: get-syslog
:END:
#+begin_src shell
dmesg --level=alert,crit,err
journalctl | grep -i "error\|warn\|fail\|acpi"
journalctl -b 1
#+end_src

** perl-rename
:PROPERTIES:
:CUSTOM_ID: perl-rename
:END:
#+begin_src shell
sudo pacman -S perl-file-rename
echo 'alias rename=perl-rename' | tee -a ~/.zshrc
#+end_src

** telnet
:PROPERTIES:
:CUSTOM_ID: telnet
:END:
#+begin_src shell
pacman -S inetutils xinetd
#+end_src

** tigervnc
:PROPERTIES:
:CUSTOM_ID: tigervnc
:END:
#+begin_src shell
$ sudo pacman -S tigervnc

$ sudo vim /etc/tigervnc/vncserver.users
------------------
:1={USER_NAME}  ## replace your user name here

$ vncpasswd

$ cat ~/.vnc/config
session=gnome
geometry=1920x1080
localhost
alwaysshared

$ sudo systemctl start vncserver@:1.service
$ sudo systemctl enable vncserver@:1.service
#+end_src

then use ssh:

#+begin_src shell
vim ~/.ssh/config

Host archlinux
    HostName 10.0.0.1 # use your ip here
    User gerald
    LocalForward 5901 localhost:5901
#+end_src

then run the command:

#+begin_src shell
// type your password and login
ssh archlinux

// use the vncviewer command
vncviewer localhost:5901
#+end_src

copy from [[https://wiki.archlinux.org/title/TigerVNC][TigerVNC]] also
see
[[https://cxybb.com/article/lxyoucan/116780297][archlinux安装配置vnc+openbox]]
also see
[[https://www.tecmint.com/install-tightvnc-access-remote-desktop-in-linux/][How
to Install TightVNC to Access Remote Desktops in Linux]]

** disable sleep
:PROPERTIES:
:CUSTOM_ID: disable-sleep
:END:
#+begin_src shell
sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
#+end_src

copy from [[https://zhuanlan.zhihu.com/p/415661679][禁止ubuntu
20.04自动休眠]]

** filename higher than 255 characters
:PROPERTIES:
:CUSTOM_ID: filename-higher-than-255-characters
:END:
#+begin_src shell
/usr/src/linux-headers-2.6.38-10/include/linux/limits.h

 #define NAME_MAX         255    /* # chars in a file name */
 #define PATH_MAX        4096    /* # chars in a path name including nul */
#+end_src

copy from
[[https://serverfault.com/questions/9546/filename-length-limits-on-linux][Filename
length limits on linux?]]

** disable gnome-keyring ssh integration
:PROPERTIES:
:CUSTOM_ID: disable-gnome-keyring-ssh-integration
:END:
#+begin_src shell
(cat /etc/xdg/autostart/gnome-keyring-ssh.desktop; echo Hidden=true) > ~/.config/autostart/gnome-keyring-ssh.desktop
#+end_src

copy from
[[https://askubuntu.com/questions/545172/how-do-i-disable-gnome-keyring-ssh-integration][How
do I disable gnome-keyring ssh integration?]]

** mount disk in /etc/fstab
:PROPERTIES:
:CUSTOM_ID: mount-disk-in-etcfstab
:END:
#+begin_example
#UUID=ebb41841-85fd-4d22-9f33-c88348ff18c4   /          btrfs deafults 0 0
#/dev/sda1   /          btrfs       defaults    0 0
PARTUUID=ebb41841-85fd-4d22-9f33-c88348ff18c4   /       btrfs       defaults    0 0
#+end_example

** change nic interface name
:PROPERTIES:
:CUSTOM_ID: change-nic-interface-name
:END:
#+begin_src shell
cat /sys/class/net/enp0s4/addres

sudo vim /etc/udev/rules.d/10-network.rules
--------------------------------------------
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="aa:bb:cc:dd:ee:ff", NAME="net1"
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="ff:ee:dd:cc:bb:aa", NAME="net0"
#+end_src

copy from [[https://wiki.archlinux.org/title/Network_configuration#Change_interface_name][Change interface name]]

** android filesystem support
:PROPERTIES:
:CUSTOM_ID: android-filesystem-support
:END:
#+begin_src shell
sudo pacman -S mtpfs
yay -S jmtpfs

sudo chmod 777 /mnt                      //this is very import

jmtpfs /mnt                             //to mount android to /mnt

fusermount -u /mnt                      //umount mnt
#+end_src

copy from [[https://www.jianshu.com/p/e90f9e45fe62][How to Transfer Files from Arch Linux to Android]]

** at batch command line
:PROPERTIES:
:CUSTOM_ID: at-batch-command-line
:END:
#+begin_src shell
sudo pacman -S at
sudo systemctl enable --now atd
at 09:00 -f /home/linuxize/script.sh

at 09:00 <<END
command_to_be_run
END

atq
// get the run command with the job id number, 3 is in the output list of the atq
at -c 3
atrm 1
#+end_src

** lldb-mi
:PROPERTIES:
:CUSTOM_ID: lldb-mi
:END:
#+begin_src shell
yay -S lldb-mi-git
#+end_src

** texlive and pandoc
:PROPERTIES:
:CUSTOM_ID: texlive-and-pandoc
:END:
#+begin_src shell
// sudo vim /etc/pacman.conf
-----------------
// [Clansty]
// SigLevel = Never
// Server = https://repo.lwqwq.com/archlinux/$arch
// Server = https://pacman.ltd/archlinux/$arch
// Server = https://repo.clansty.com/archlinux/$arch

// sudo pacman -Suw texlive-full
// sudo pacman -S texlive-full

// wget -c https://pacman.ltd/archlinux/pool/texlive-full-20220220-1-x86_64.pkg.tar.zst
// sudo pacman -U texlive-full-20220220-1-x86_64.pkg.tar.zst

sudo pacman -S pandoc texlive-core texlive-latexextra texlive-fontsextra texlive-langchinese texlive-most texlive-lang texlive-pstricks
yay -S ttf-sarasa-ui-sc
pandoc README.md -o README.pdf --pdf-engine=xelatex -V CJKmainfont='Sarasa UI SC'
pandoc README.md -o README.docx
#+end_src

copy from [[https://zhuanlan.zhihu.com/p/417566961][ArchLinux 安装 TeXLive]]

** appflowy
:PROPERTIES:
:CUSTOM_ID: appflowy
:END:
#+begin_src shell
yay -S appflowy-bin
#+end_src

** wireshark-cli
:PROPERTIES:
:CUSTOM_ID: wireshark-cli
:END:
#+begin_src shell
sudo pacman -S wireshark-cli
#+end_src

** minio
:PROPERTIES:
:CUSTOM_ID: minio
:END:
#+begin_src shell
sudo pacman -S minio minio-client
#+end_src

** wine
:PROPERTIES:
:CUSTOM_ID: wine
:END:
#+begin_src shell
sudo pacman -S wine-mono wine
#+end_src

** cronie
:PROPERTIES:
:CUSTOM_ID: cronie
:END:
#+begin_src shell
sudo pacman -S cronie
sudo systemctl enable --now cronie.service
EDITOR="emacs -nw" crontab -e
#+end_src

** alsamixer
:PROPERTIES:
:CUSTOM_ID: alsamixer
:END:
#+begin_src shell
sudo pacman -S alsa-utils
alsamixer
// save the setting
sudo alsactl store
#+end_src

** podman start error
:PROPERTIES:
:CUSTOM_ID: podman-start-error
:END:
#+begin_src shell
$ podman run -it --rm --entrypoint=/bin/bash --privileged --ulimit nofile=262144:262144 -v $PWD:/work -p 9000:9000 -p 18123:8123 yandex/clickhouse-server:21.3.20.1
Error: crun: error stat'ing file `/dev/vboxusb/001/007`: Permission denied: OCI permission denied
#+end_src

it might be error to be fixed by：
[[https://github.com/containers/podman/issues/13899][Privileged containers cannot be restarted if host devices changed]]

** docker
:PROPERTIES:
:CUSTOM_ID: docker
:END:
#+begin_src shell
sudo pacman -S docker
sudo usermod -aG docker $USER
sudo systemctl enable --now docker
#+end_src

** lld
:PROPERTIES:
:CUSTOM_ID: lld
:END:
#+begin_src shell
sudo pacman -S lld
#+end_src

copy from
[[https://stackoverflow.com/questions/70272393/cargo-build-failed-with-note-collect2-fatal-error-cannot-find-ld][Cargo
build failed with = note: collect2: fatal error: cannot find 'ld']]

** zram-generator
:PROPERTIES:
:CUSTOM_ID: zram-generator
:END:
#+begin_src shell
sudo pacman -S zram-generator

echo "[zram0]
zram-size = ram / 2" | sudo tee -a /etc/systemd/zram-generator.conf

sudo systemctl daemon-reload

sudo systemctl start /dev/zram0

zramctl
#+end_src

swap is no more needed.
copy from [[https://github.com/systemd/zram-generator][systemctl start /dev/zram0]]
The reason why choose zram: 1, the kubernetes dislike swap
2, the zram is much more high performance.

Or change the zram-generator.conf:

#+begin_example
[zram0]
zram-fraction = 1
max-zram-size=none
#+end_example

copy from [[https://medium.com/nerd-for-tech/dynamically-adjust-swap-zram-size-in-fedora-linux-78cd712808f2][Dynamically Increase SWAP (ZRAM) Size in Linux]]

kubernetes does not accept swap, the zram is also not accepted. Do not
install zram.

** visual-studio-code-bin
:PROPERTIES:
:CUSTOM_ID: visual-studio-code-bin
:END:
for unreal engine

#+begin_src shell
yay -S visual-studio-code-bin
#+end_src

** unreal engine
:PROPERTIES:
:CUSTOM_ID: unreal-engine
:END:
#+begin_src shell
yay -S aur/unreal-engine-bin
## download Linux_Unreal_Engine_5.1.0.zip ~/.cache/yay/unreal-engine-bin
yay -S aur/unreal-engine-bin
#+end_src

** install flutter
:PROPERTIES:
:CUSTOM_ID: install-flutter
:END:
#+begin_src shell
sudo pacman -S flutter
sudo usermod -aG flutterusers $USER
#+end_src

** /usr/bin/dkms: line 1033: sha512: command not found
:PROPERTIES:
:CUSTOM_ID: usrbindkms-line-1033-sha512-command-not-found
:END:
#+begin_src shell
sudo ln -s /usr/bin/sha512sum /usr/bin/sha512
#+end_src

copy from
[[https://bbs.archlinux.org/viewtopic.php?id=277700][/usr/sbin/dkms: line 1033: sha512: command not found.]]
also see [[https://github.com/dell/dkms/issues/229][https://bbs.archlinux.org/viewtopic.php?id=277700]]

** cpupower
:PROPERTIES:
:CUSTOM_ID: cpupower
:END:
#+begin_src shell
sudo pacman -S cpupower

cpupower frequency-info

cat /etc/default/cpupower
min_freq="1.20GHz"
max_freq="2.40GHz"

sudo systemctl restart cpupower
sudo systemctl start cpupower
#+end_src

** systemd-networkd-wait-online.service fail
:PROPERTIES:
:CUSTOM_ID: systemd-networkd-wait-online.service-fail
:END:
#+begin_src shell
[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --ignore=enp0s31f6
#+end_src

copy from [[https://unix.stackexchange.com/questions/381448/systemd-networkd-wait-online-failure][systemd-networkd-wait-online failure]]

** qemu
:PROPERTIES:
:CUSTOM_ID: qemu
:END:
#+begin_src shell
sudo pacman -Syu libvirt qemu ebtables dnsmasq
sudo systemctl enable libvirtd.service --now
sudo systemctl enable virtlogd.service --now
#+end_src

copy from
[[https://medium.com/@morgan_42683/kubernetes-on-your-local-manjaro-arch-7890904c8984][Kubernetes
on your local Manjaro/Arch]]

** wpa_supplicant
:PROPERTIES:
:CUSTOM_ID: wpa_supplicant
:END:
wpa_supplicant.service:

#+begin_src shell
sudo vim /lib/systemd/system/wpa_supplicant.service
#+end_src

Find the following line.

#+begin_src shell
ExecStart=/usr/bin/wpa_supplicant -u -s -O /run/wpa_supplicant
#+end_src

change to be:

#+begin_src shell
ExecStart=/usr/bin/wpa_supplicant -u -s -c /etc/wpa_supplicant/wpa_supplicant.conf -i wlp0s20u9
Restart=always
#+end_src

then start the service

#+begin_src shell
sudo systemctl enable wpa_supplicant.service
sudo systemctl start wpa_supplicant.service
#+end_src

** mysql
:PROPERTIES:
:CUSTOM_ID: mysql
:END:
#+begin_src shell
sudo pacman -S libmysqlclient
#+end_src

** pacman update ignore package
:PROPERTIES:
:CUSTOM_ID: pacman-update-ignore-package
:END:
#+begin_example
sudo vim /etc/pacman.conf

IgnorePkg   = wpa_supplicant
#+end_example

** install nvm
:PROPERTIES:
:CUSTOM_ID: install-nvm
:END:
#+begin_src shell
sudo pacman -S nvm
echo 'source /usr/share/nvm/init-nvm.sh' >> ~/.zshrc
source ~/.zshrc
nvm install v14.2.0

## change directory
# cd project_dir
nvm use
npm install
npm run start
#+end_src

** yt-dlp
:PROPERTIES:
:CUSTOM_ID: yt-dlp
:END:
#+begin_src shell
sudo pacman -S yt-dlp

yt-dlp --proxy socks5://127.0.0.1:10808/ -R infinite -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --write-description --write-info-json --write-annotations --write-thumbnail --write-auto-sub --sub-lang en,zh-Hans --convert-subtitles srt https://www.youtube.com/watch\?v\=69h1zhIdCN0

yt-dlp --proxy socks5://127.0.0.1:10808/ -R infinite -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --write-description --write-info-json --write-annotations --write-thumbnail --write-auto-sub --sub-lang en,zh-Hans --convert-subtitles srt -a youtube-download-file.txt
#+end_src

** yt-dlp download bilibili video with high quality

login with account in firefox browser, then download videos:

#+begin_src
yt-dlp --cookies-from-browser firefox  https://www.bilibili.com/video/BV1af421R7BD
#+end_src

** yt-dlp download with auth

#+begin_src shell
python3 -m pip install -U --break-system-packages https://github.com/coletdjnz/yt-dlp-youtube-oauth2/archive/refs/heads/master.zip

yt-dlp --username oauth2  --password "" --proxy socks5://127.0.0.1:7890/ -R infinite -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'  --sub-lang zh-Hans --convert-subtitles srt youtube_url

# open chrome and input token
#+end_src

copy from https://www.reddit.com/r/youtubedl/comments/1e6bzu4/ytdlp_error_sign_in_to_confirm_youre_not_a_bot/

** julia
:PROPERTIES:
:CUSTOM_ID: julia
:END:
#+begin_src shell
yay -S community/julia
#+end_src

** install pdftk
:PROPERTIES:
:CUSTOM_ID: install-pdftk
:END:
#+begin_src shell
sudo pacman -S pdftk

pdftk input.pdf cat 1 output 1.pdf
#+end_src

** nushell starship zellij
:PROPERTIES:
:CUSTOM_ID: nushell-starship-zellij
:END:
#+begin_src shell
sudo pacman -S nushell starship zellij
#+end_src

** emacs-pretest
#+begin_src sh
yay -S emacs-pretest
#+end_src

** enable systemd-timesyncd
#+begin_src rust
sudo systemctl enable systemd-timesyncd
sudo systemctl start systemd-timesyncd
#+end_src

copy from [[http://blog.lujun9972.win/blog/2018/10/16/%E5%9C%A8archlinux%E4%B8%8A%E8%BF%9B%E8%A1%8C%E6%97%B6%E9%92%9F%E5%90%8C%E6%AD%A5/index.html][在Archlinux上进行时钟同步
]]
