* hyper 1.0 code snippet


** hyper 1.0 how to get Incoming body

#+begin_src rust
use http_body_util::BodyExt;
async fn echo(req: Request<hyper::body::Incoming>) -> Result<Response<BoxBody<Bytes, hyper::Error>>, hyper::Error> {
  let reversed_body = req.collect().await?.to_bytes().to_vec();
#+end_src

or
#+begin_src rust
use http_body_util::BodyExt;
async fn echo(req: Request<hyper::body::Incoming>) -> Result<Response<BoxBody<Bytes, hyper::Error>>, hyper::Error> {

  let (parts, body) = req.into_parts();
  let body = body.collect().await?.to_bytes().to_vec();
#+end_src

** Body usage

#+begin_src rust
use hyper::body::Body;

pub type BoxError = Box<dyn std::error::Error + Send + Sync>;

Boxed(Pin<Box<dyn Body<Data = Bytes, Error = BoxError> + Send + Sync + 'static>>),
#+end_src

** http_body_util BodyExt trait
#+begin_src rust
pub trait BodyExt: Body {
    // Provided methods
    fn frame(&mut self) -> Frame<'_, Self> ⓘ
       where Self: Unpin { ... }
    fn map_frame<F, B>(self, f: F) -> MapFrame<Self, F>
       where Self: Sized,
             F: FnMut(Frame<Self::Data>) -> Frame<B>,
             B: Buf { ... }
    fn map_err<F, E>(self, f: F) -> MapErr<Self, F>
       where Self: Sized,
             F: FnMut(Self::Error) -> E { ... }
    fn boxed(self) -> BoxBody<Self::Data, Self::Error>
       where Self: Sized + Send + Sync + 'static { ... }
    fn boxed_unsync(self) -> UnsyncBoxBody<Self::Data, Self::Error>
       where Self: Sized + Send + 'static { ... }
    fn collect(self) -> Collect<Self> ⓘ
       where Self: Sized { ... }
}

impl<T: ?Sized> BodyExt for T where T: http_body::Body {}
#+end_src

BodyExt auto add method to Body trait object.

** hyper Incoming

#+begin_src rust
impl Body for Incoming {
    type Data = Bytes;
    type Error = crate::Error;
}
#+end_src


** collect function

#+begin_src rust
fn collect(self) -> combinators::Collect<Self>
    where
        Self: Sized,
    {
        combinators::Collect {
            body: self,
            collected: Some(crate::Collected::default()),
        }
    }
#+end_src

** Collect

#+begin_src rust
pin_project! {
    /// Future that resolves into a [`Collected`].
    ///
    /// [`Collected`]: crate::Collected
    pub struct Collect<T>
    where
        T: Body,
        T: ?Sized,
    {
        pub(crate) collected: Option<crate::Collected<T::Data>>,
        #[pin]
        pub(crate) body: T,
    }
}

impl<T: Body + ?Sized> Future for Collect<T> {
    type Output = Result<crate::Collected<T::Data>, T::Error>;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> std::task::Poll<Self::Output> {
        let mut me = self.project();

        loop {
            let frame = futures_util::ready!(me.body.as_mut().poll_frame(cx));

            let frame = if let Some(frame) = frame {
                frame?
            } else {
                return Poll::Ready(Ok(me.collected.take().expect("polled after complete")));
            };

            me.collected.as_mut().unwrap().push_frame(frame);
        }
    }
}
#+end_src

** Collected

#+begin_src rust
#[derive(Debug)]
pub struct Collected<B> {
    bufs: BufList<B>,
    trailers: Option<HeaderMap>,
}

impl<B: Buf> Collected<B> {
  /// Convert this body into a [`Bytes`].
    pub fn to_bytes(mut self) -> Bytes {
        self.bufs.copy_to_bytes(self.bufs.remaining())
    }
}
#+end_src

** Bytes to_vec() method

#+begin_src rust
pub struct Bytes {
    ptr: *const u8,
    len: usize,
    // inlined "trait object"
    data: AtomicPtr<()>,
    vtable: &'static Vtable,
}

pub(crate) struct Vtable {
    /// fn(data, ptr, len)
    pub clone: unsafe fn(&AtomicPtr<()>, *const u8, usize) -> Bytes,
    /// fn(data, ptr, len)
    ///
    /// takes `Bytes` to value
    pub to_vec: unsafe fn(&AtomicPtr<()>, *const u8, usize) -> Vec<u8>,
    /// fn(data, ptr, len)
    pub drop: unsafe fn(&mut AtomicPtr<()>, *const u8, usize),
}

#+end_src

** http_doby body type conversion

Incoming -> Collect -> Collected -> Bytes -> Vec<u8>

** 0.x change to 1.0
#+begin_src rust
0.x       1.x
  Body => Incoming
#+end_src

** hyper Read, Write trait impl example

#+begin_src rust
use std::task::{Context, Poll};

use hyper::rt::{Read, ReadBufCursor, Write};

use hyper_util::{
    client::legacy::connect::{Connected, Connection},
    rt::TokioIo,
};
pub use tokio_native_tls::TlsStream;

/// A stream that might be protected with TLS.
pub enum MaybeHttpsStream<T> {
    /// A stream over plain text.
    Http(T),
    /// A stream protected with TLS.
    Https(TokioIo<TlsStream<TokioIo<T>>>),
}

impl<T: Read + Write + Unpin> Read for MaybeHttpsStream<T> {
    #[inline]
    fn poll_read(
        self: Pin<&mut Self>,
        cx: &mut Context,
        buf: ReadBufCursor<'_>,
    ) -> Poll<Result<(), io::Error>> {
        match Pin::get_mut(self) {
            MaybeHttpsStream::Http(s) => Pin::new(s).poll_read(cx, buf),
            MaybeHttpsStream::Https(s) => Pin::new(s).poll_read(cx, buf),
        }
    }
}

impl<T: Write + Read + Unpin> Write for MaybeHttpsStream<T> {
    #[inline]
    fn poll_write(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &[u8],
    ) -> Poll<Result<usize, io::Error>> {
        match Pin::get_mut(self) {
            MaybeHttpsStream::Http(s) => Pin::new(s).poll_write(cx, buf),
            MaybeHttpsStream::Https(s) => Pin::new(s).poll_write(cx, buf),
        }
    }
  }
#+end_src

copy from https://github.com/hyperium/hyper-tls

** Connect, ConnectSvc trait and impl example

#+begin_src rust
pub(super) mod sealed {
    use std::error::Error as StdError;
    use std::future::Future;

    use ::http::Uri;
    use hyper::rt::{Read, Write};

    use super::Connection;

    /// Connect to a destination, returning an IO transport.
    ///
    /// A connector receives a [`Uri`](::http::Uri) and returns a `Future` of the
    /// ready connection.
    ///
    /// # Trait Alias
    ///
    /// This is really just an *alias* for the `tower::Service` trait, with
    /// additional bounds set for convenience *inside* hyper. You don't actually
    /// implement this trait, but `tower::Service<Uri>` instead.
    // The `Sized` bound is to prevent creating `dyn Connect`, since they cannot
    // fit the `Connect` bounds because of the blanket impl for `Service`.
    pub trait Connect: Sealed + Sized {
        #[doc(hidden)]
        type _Svc: ConnectSvc;
        #[doc(hidden)]
        fn connect(self, internal_only: Internal, dst: Uri) -> <Self::_Svc as ConnectSvc>::Future;
    }

    pub trait ConnectSvc {
        type Connection: Read + Write + Connection + Unpin + Send + 'static;
        type Error: Into<Box<dyn StdError + Send + Sync>>;
        type Future: Future<Output = Result<Self::Connection, Self::Error>> + Unpin + Send + 'static;

        fn connect(self, internal_only: Internal, dst: Uri) -> Self::Future;
    }

    impl<S, T> Connect for S
    where
        S: tower_service::Service<Uri, Response = T> + Send + 'static,
        S::Error: Into<Box<dyn StdError + Send + Sync>>,
        S::Future: Unpin + Send,
        T: Read + Write + Connection + Unpin + Send + 'static,
    {
        type _Svc = S;

        fn connect(self, _: Internal, dst: Uri) -> tower::util::Oneshot<S, Uri> {
            tower::util::Oneshot::new(self, dst)
        }
    }

    impl<S, T> ConnectSvc for S
    where
        S: tower_service::Service<Uri, Response = T> + Send + 'static,
        S::Error: Into<Box<dyn StdError + Send + Sync>>,
        S::Future: Unpin + Send,
        T: Read + Write + Connection + Unpin + Send + 'static,
    {
        type Connection = T;
        type Error = S::Error;
        type Future = tower::util::Oneshot<S, Uri>;

        fn connect(self, _: Internal, dst: Uri) -> Self::Future {
            tower::util::Oneshot::new(self, dst)
        }
    }

    impl<S, T> Sealed for S
    where
        S: tower_service::Service<Uri, Response = T> + Send,
        S::Error: Into<Box<dyn StdError + Send + Sync>>,
        S::Future: Unpin + Send,
        T: Read + Write + Connection + Unpin + Send + 'static,
    {
    }

    pub trait Sealed {}
    #[allow(missing_debug_implementations)]
    pub struct Internal;
}
#+end_src

copy from hyper_util project

** trait alias

#+begin_src rust
trait Valid: PartialOrd + Display + PartialEq + Clone {}

impl<T: PartialOrd + Display + PartialEq + Clone> Valid for T {}

struct Foobar<T> {
    t: T,
}

impl<T> Foobar<T> {
    fn something_foo(&self)
    where
        T: Foo,
    { ... }

    fn something_bar(&self)
    where
        T: Bar,
    { ... }
}

trait Trait: PartialOrd + Display + PartialEq +Clone;

impl<T> Trait for T where T: PartialOrd + Display+ PartialEq + Clone;
#+end_src

copy from [[https://www.reddit.com/r/rust/comments/1582jku/how_can_one_create_a_trait_alias/][How can one create a trait alias?]]


** changelog
#+begin_quote
empty 改为 Empty
Body 改为 http_body_util::combinators::BoxBody<bytes::Bytes, std::io::Error>
addrIncoming 删除
make_service_fn 删除
hyper::Server 改为 hyper_util::server::conn::auto
hyper::server::conn::AddrStream 删除
hyper::service::Service 删除 poll_ready 方法
hyper::server::accept::from_stream(incoming.into_stream()) 改为 hyper_util::rt::TokioExecutor
hyper::body::to_bytes 改为 http-body-util::Collected::to_bytes()
hyper::body::aggregate 改为 http-body-util::Collected::aggregate
hyper::Body::wrap_stream(stream) 改为BoxBody::new(http_body_util::StreamBody::new(
            SyncStream::new(
                stream
                    .map_ok(|data| Frame::data(data.into()))
                    .map_err(Into::into),
            ),
        ))
Body::from ?
#+end_quote

** Incoming
Incoming to be bytes is ok, but bytes how to be Incoming? No, bytes cannot change to be Incoming

see https://github.com/tauri-apps/tauri/pull/12240
*** Incoming change to be Full<Bytes>
*** change to use async closure, which is Future object.


** migration code snippets
Cargo.toml
#+begin_src rust
  [dependencies]
  (...)
- hyper = { version = "0.14", features = ["server", "http1", "http2", "tcp"] }

+ hyper = { version = "1", features = ["server", "http1", "http2"] }
+ hyper-util = { version = "^0.1", features = ["server", "http1", "http2", "tokio"] }
+ http-body-util = "^0.1"
#+end_src

Body change log
#+begin_src rust
- use hyper::Body;

+ use hyper::body::{Bytes, Incoming}};
#+end_src

std::body::* Structs implementing Body Trait are available. They are such as std::body::Bytes and std::body::Incoming.
#+begin_src rust
- pub async fn handle(
-     req: Request<Body>,
-     app_state: Arc<Mutex<Config>>,
- ) -> Result<Response<Body>, Error> {

+ type BoxBody = http_body_util::combinators::BoxBody<Bytes, Infallible>;
+ pub async fn handle(
+     req: Request<Incoming>,
+     app_state: Arc<Mutex<Config>>,
+ ) -> Result<Response<BoxBody>, Error> {
#+end_src


whole bulk full of the frames at once with BoxBody:
#+begin_src rust
- let body_bytes = hyper::body::to_bytes(request_body).await.unwrap();

+ let body_bytes = request_body
+                 .boxed() // here, `BoxBody` comes !
+                 .collect()
+                 .await
+                 .expect("failed to collect request incoming body")
+                 .to_bytes();
#+end_src


The client case was similar with it.

#+begin_src rust
- hyper::body::to_bytes;
- (...)
- let response = client.request(request).await.unwrap();
- (...)
- let response_body_str =
-         String::from_utf8(to_bytes(response.into_body()).await.unwrap().to_vec()).unwrap();

+ use http_body_util::{BodyExt, Empty, Full};
+ (...)
+ let request_body = Full::new(Bytes::from(body.unwrap().to_owned())).boxed()
+ (...)
+ let response_body_bytes = response
+         .into_body()
+         .boxed()
+         .collect()
+         .await
+         .unwrap()
+         .to_bytes();
+ let response_body_str = String::from_utf8(body_bytes.into()).unwrap();
#+end_src

copy from [[https://scqr.net/en/blog/2024/05/21/hyper-rust-upgrade-to-v1-body-became-trait/][hyper (Rust) upgrade to v1: Body became Trait]]
