* tuono

** installation

#+begin_src shell
cargo install tuono
#+end_src

copy from [[https://tuono.dev/documentation/installation][Installation]]

** init project

#+begin_src shell
tuono new tuono-tutorial
cd tuono-tutorial
#+end_src

** tuono build

*** install the typescript package

#+begin_src shell
bun i
#+end_src

*** start dev

#+begin_src shell
tuono dev
#+end_src

*** build the typescript code part

this _build_ command will genenrate a _out_ directory.

#+begin_src shell
tuono build
#+end_src


*** build the rust code part

#+begin_src shell
cargo build
#+end_src

*** build the rust code part

#+begin_src shell
cargo build --release
#+end_src

** deployment

*** copy the tuono from the target directory

#+begin_src shell
cp target/release/tuono .
# in the same directory, with the out directory
./tuono
#+end_src

copy from [[https://tuono.dev/documentation/tutorial/development-setup][Start the dev environment]]

Then open http://localhost:3000/ on the browser.


** debug tuono

#+begin_src shell
$ cd tuono
$ pnpm i & pnpm build
$ cargo build
$ cd  examples/tuono-app
$ pnpm i
$ ../../target/debug/tuono dev

  ⚡ Tuono v0.17.0
  Ready at: http://localhost:3000

  GET / 200 in 43ms
  GET / 200 in 40ms
#+end_src


** tuono debug

with `pnpm i`, then `tuono dev`, the tuono will launch, sometimes it run into trouble.

*** tuono build

#+begin_src shell
$ tuono build

Error: Cannot find module '@swc/core-darwin-x64'
Require stack:
#+end_src

**** add the missing

#+begin_src shell
pnpm i -D @swc/core-darwin-x64
#+end_src

**** continue to run tuono build

#+begin_src shell
tuono build
#+end_src

*** check the .tuono directory

#+begin_src shell
$ ls .tuono/config
config.json config.mjs
#+end_src

if the _config.json_ is not found, or the _config_ directory not found in _.tuono_, it might be the some node library missing in the project.

the config.json might be like this:
#+begin_src typescript
{"server":{"host":"localhost","port":3000}}
#+end_src

*** it might be the old outdated packages

#+begin_src shell
nuc -u
 @types/react      19.0.2  →  19.0.8
 @types/react-dom  19.0.2  →  19.0.3
 tuono             0.17.0  →  0.17.6
 typescript         5.6.3  →   5.7.3
pnpm i
tuono dev
#+end_src

It might also need to update tuono cli:

#+begin_src shell
cargo install --force tuono
#+end_src

** node default port is 3001, tuono default port is 3000

#+begin_src shell
$ lsof -i :3001
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    57445 user   57u  IPv4 0xb3d09473786addda      0t0  TCP localhost:redwood-broker (LISTEN)

$ lsof -i :3000
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
tuono   57504 user    9u  IPv4 0xcd75cedf64ddec7b      0t0  TCP localhost:hbci (LISTEN)
#+end_src


** deploy tuono application

*** config.json

#+begin_src typescript
{"server":{"host":"localhost","port":3000}}
#+end_src

*** tuono compile

#+begin_src shell
tuono build

cargo build --release

# in the directory which contains config.json file
./target/release/tuono
#+end_src

This _tuono_ file is just compiled in the _Cargo.toml_ file.