* tuono

** installation

#+begin_src shell
cargo install tuono
#+end_src

copy from [[https://tuono.dev/documentation/installation][Installation]]

** init project

#+begin_src shell
tuono new tuono-tutorial
cd tuono-tutorial
#+end_src

** tuono build

*** install the typescript package

#+begin_src shell
bun i
#+end_src

*** start dev

#+begin_src shell
tuono dev
#+end_src

*** build the typescript code part

this _build_ command will genenrate a _out_ directory.

#+begin_src shell
tuono build
#+end_src


*** build the rust code part

#+begin_src shell
cargo build
#+end_src

*** build the rust code part

#+begin_src shell
cargo build --release
#+end_src

** deployment

*** copy the tuono from the target directory

#+begin_src shell
cp target/release/tuono .
# in the same directory, with the out directory
./tuono
#+end_src

copy from [[https://tuono.dev/documentation/tutorial/development-setup][Start the dev environment]]

Then open http://localhost:3000/ on the browser.


** debug tuono

#+begin_src shell
$ cd tuono
$ pnpm i & pnpm build
$ cargo build
$ cd  examples/tuono-app
$ pnpm i
$ ../../target/debug/tuono dev

  ⚡ Tuono v0.17.0
  Ready at: http://localhost:3000

  GET / 200 in 43ms
  GET / 200 in 40ms
#+end_src


** tuono debug

with `pnpm i`, then `tuono dev`, the tuono will launch, sometimes it run into trouble.

*** tuono build

#+begin_src shell
$ tuono build

Error: Cannot find module '@swc/core-darwin-x64'
Require stack:
#+end_src

**** add the missing

#+begin_src shell
pnpm i -D @swc/core-darwin-x64
#+end_src

**** continue to run tuono build

#+begin_src shell
tuono build
#+end_src

*** check the .tuono directory

#+begin_src shell
$ ls .tuono/config
config.json config.mjs
#+end_src

if the _config.json_ is not found, or the _config_ directory not found in _.tuono_, it might be the some node library missing in the project.

the config.json might be like this:
#+begin_src json
{"server":{"host":"localhost","port":3000}}
#+end_src