#!/bin/sh
wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-1.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-2.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-3.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-4.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-5.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-6.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-7.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-8.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-9.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-10.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-11.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-12.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-13.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-14.jigdo  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-1.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-2.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-3.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-4.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-5.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-6.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-7.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-8.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-9.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-10.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-11.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-12.jigdo ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-1.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-2.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-3.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-4.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-5.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-6.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-7.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-8.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-9.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-10.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-11.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-12.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-13.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-14.template  ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-1.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-2.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-3.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-4.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-5.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-6.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-7.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-8.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-9.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-10.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-11.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-12.template ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/source/iso-dvd/SHA256SUMS -O debian-9.0.0-source.sha256sums ; \
	wget -c http://cdimage.debian.org/debian-cd/9.0.0/amd64/iso-dvd/SHA256SUMS -O debian-9.0.0-amd64.sha256sums ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-1.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-2.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-3.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-4.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-5.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-6.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-7.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-8.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-9.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-10.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-11.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-12.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-13.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/amd64/jigdo-dvd/debian-9.0.0-amd64-DVD-14.jigdo  ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-1.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-2.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-3.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-4.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-5.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-6.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-7.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-8.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-9.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-10.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-11.jigdo ; \
	jigdo-lite --noask http://cdimage.debian.org/debian-cd/9.0.0/source/jigdo-dvd/debian-9.0.0-source-DVD-12.jigdo
