* mongodb add user and auth

** mongodb installation

#+begin_src shell
sudo yum install -y mongodb-org
#+end_src

To set up authentication in MongoDB and add a user with a password,
follow these steps:

*** Start MongoDB without access control
:PROPERTIES:
:CUSTOM_ID: start-mongodb-without-access-control
:END:
If you haven't set up authentication before, you need to start MongoDB
without access control to add the initial user.

#+begin_src sh
sudo systemctl start mongod
#+end_src

*** Connect to MongoDB
:PROPERTIES:
:CUSTOM_ID: connect-to-mongodb
:END:
Open a new terminal and connect to the MongoDB instance.

#+begin_src sh
mongosh
#+end_src

*** Switch to the =admin= database
:PROPERTIES:
:CUSTOM_ID: switch-to-the-admin-database
:END:
#+begin_src shell
use admin
#+end_src

*** Create the administrative user
:PROPERTIES:
:CUSTOM_ID: create-the-administrative-user
:END:
Create a user with the =userAdminAnyDatabase= role. Replace =admin= and
=password= with your desired username and password.

#+begin_src shell
db.createUser(
  {
    user: "admin",
    pwd: "password",
    roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
  }
)
#+end_src

*** Enable Authentication in the Configuration File
:PROPERTIES:
:CUSTOM_ID: enable-authentication-in-the-configuration-file
:END:
Edit the MongoDB configuration file (=mongod.conf=). Find the security
section and add the following lines:

#+begin_quote
security:
  authorization: "enabled"
#+end_quote

*** Restart MongoDB with Authentication Enabled
:PROPERTIES:
:CUSTOM_ID: restart-mongodb-with-authentication-enabled
:END:
Stop the MongoDB instance and restart it with the configuration file.

#+begin_src sh
sudo systemctl restart mongod
#+end_src

*** Connect to MongoDB with Authentication
:PROPERTIES:
:CUSTOM_ID: connect-to-mongodb-with-authentication
:END:
Open a new terminal and connect to MongoDB using the newly created admin
user.

#+begin_src sh
mongosh -u "admin" -p "password" --authenticationDatabase "admin"
#+end_src

*** Add a New User with a Password
:PROPERTIES:
:CUSTOM_ID: add-a-new-user-with-a-password
:END:
Switch to the database where you want to add the user and create a new
user with the desired roles. Replace =myUserAdmin=, =myPassword=,
=myDatabase=, and the role details with your desired values.

#+begin_src shell
use myDatabase

db.createUser(
  {
    user: "myUserAdmin",
    pwd: "myPassword",
    roles: [ { role: "readWrite", db: "myDatabase" } ]
  }
)
#+end_src

** mongodb 4.2

Starting from Mongodb version 6.0 mongo was replaced by mongosh.

#+begin_src shell
mongo
> use admin
> db.createUser({user:"admin_user",pwd:"password123",roles:["root"]})

> db.createUser({user:"root",pwd:"testcode123",roles:[{role:"readWrite",db:"database_1"}]})
#+end_src
