* dart gorouter

** go vs push
#+begin_quote
Think of go as a way to jump to a new route. This will modify the underlying navigation stack
if the new route is not a sub-route of the old one.

On the other hand, push will always push the destination route on top of the existing navigation stack.

If you can, try to not use push and always prefer go instead,
since this doesn't require you to set special flags (such as optionURLReflectsImperativeAPIs),
and plays nice with deep links on mobile.
#+end_quote

copy from [[https://codewithandrea.com/articles/flutter-navigation-gorouter-go-vs-push/][Flutter Navigation with GoRouter: Go vs Push]]

** StatefulShellRoute example

#+begin_src dart
// Create keys for `root` & `section` navigator avoiding unnecessary rebuilds
final _rootNavigatorKey = GlobalKey<NavigatorState>();
final _sectionNavigatorKey = GlobalKey<NavigatorState>();


final router = GoRouter(
  navigatorKey: _rootNavigatorKey,
  initialLocation: '/feed',
  routes: <RouteBase>[
    StatefulShellRoute.indexedStack(
      builder: (context, state, navigationShell) {
        // Return the widget that implements the custom shell (e.g a BottomNavigationBar).
        // The [StatefulNavigationShell] is passed to be able to navigate to other branches in a stateful way.
        return ScaffoldWithNavbar(navigationShell);
      },
      branches: [
        // The route branch for the 1º Tab
        StatefulShellBranch(
          navigatorKey: _sectionNavigatorKey,
          // Add this branch routes
          // each routes with its sub routes if available e.g feed/uuid/details
          routes: <RouteBase>[
            GoRoute(
              path: '/feed',
              builder: (context, state) => const FeedPage(),
              routes: <RouteBase>[
                GoRoute(
                  path: 'detail',
                  builder: (context, state) => const FeedDetailsPage(),
                )
              ],
            ),
          ],
        ),

        // The route branch for 2º Tab
        StatefulShellBranch(routes: <RouteBase>[
          // Add this branch routes
          // each routes with its sub routes if available e.g shope/uuid/details
          GoRoute(
            path: '/shope',
            builder: (context, state) => const ShopePage(),
          ),
        ])
      ],
    ),
  ],
);


class ScaffoldWithNavbar extends StatelessWidget {
  const ScaffoldWithNavbar(this.navigationShell, {super.key});

  /// The navigation shell and container for the branch Navigators.
  final StatefulNavigationShell navigationShell;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: navigationShell,
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: navigationShell.currentIndex,
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
          BottomNavigationBarItem(icon: Icon(Icons.shop), label: 'Shope'),
        ],
        onTap: _onTap,
      ),
    );
  }

  void _onTap(index) {
    navigationShell.goBranch(
      index,
      // A common pattern when using bottom navigation bars is to support
      // navigating to the initial location when tapping the item that is
      // already active. This example demonstrates how to support this behavior,
      // using the initialLocation parameter of goBranch.
      initialLocation: index == navigationShell.currentIndex,
    );
  }
}

#+end_src

copy from [[https://juejin.cn/post/7270343009790853172][Flutter go_router 路由管理全面指南]]

** go_router architeture

GoRouter
└─ StatefulShellRoute
    ├─ StatefulShellBranch
    │   └─ GoRoute('/a')
    │      └─ GoRoute('details')
    └─ StatefulShellBranch
        └─ GoRoute('/b')
            └─ GoRoute('details')

copy from [[https://codewithandrea.com/articles/flutter-bottom-navigation-bar-nested-routes-gorouter/][Flutter Bottom Navigation Bar with Stateful Nested Routes using GoRouter]]

** Navigate Without Context with GoRouter and Riverpod in Flutter

#+begin_src dart
// some button callback
onPressed: () async {
  try {
    // get the database from a provider (using Riverpod)
    final database = ref.read(databaseProvider);
    // do some async work
    await database.submit(someFormData);
    // on success, pop the route if the widget is still mounted
    if (context.mounted) {
      context.pop();
    }
  } catch (e, st) {
    // TODO: show alert error
  }
}
#+end_src

1. Pass the BuildContext as an argument

#+begin_src dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class LeaveReviewController extends AutoDisposeAsyncNotifier<void> {
  // @override build method

  Future<void> submitReview({
    required ProductID productId,
    required double rating,
    required String comment,
    required BuildContext context,
  }) {
    // all the previous logic here
    state = await AsyncValue.guard(...);
    // then do this:
    if (state.hasError == false) {
      if (context.mounted) {
        // pop the current route (uses GoRouter extension)
        context.pop();
      }
    }
  }
}
#+end_src

2. Use an onSuccess callback
#+begin_src dart
class LeaveReviewController extends AutoDisposeAsyncNotifier<void> {
  // @override build method

  Future<void> submitReview({
    required ProductID productId,
    required double rating,
    required String comment,
    required VoidCallback onSuccess,
  }) {
    // all the previous logic here
    state = await AsyncValue.guard(...);
    // then do this:
    if (state.hasError == false) {
      onSuccess();
    }
  }
}


onPressed: () => ref.read(leaveReviewControllerProvider.notifier)
  .submitReview(
    productId: widget.productId,
    rating: _rating, // get the rating score from a local state variable
    comment: _controller.text, // get the text from the TextEditingController
    onSuccess: context.pop, // pop using GoRouter extension
  ),
#+end_src


3. Navigate without context using ref.read(goRouterProvider)
#+begin_src dart
final goRouterProvider = Provider<GoRouter>((ref) {
  return GoRouter(...);
});

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final goRouter = ref.watch(goRouterProvider);
    return MaterialApp.router(
      routerConfig: goRouter,
      ...
    );
  }
}


class LeaveReviewController extends AutoDisposeAsyncNotifier<void> {
  // @override build method

  Future<void> submitReview({
    required ProductID productId,
    required double rating,
    required String comment,
  }) {
    // all the previous logic here
    state = await AsyncValue.guard(...);
    // then do this:
    if (state.hasError == false) {
      // get the GoRouter instance and call pop on it
      ref.read(goRouterProvider).pop();
    }
  }
}
#+end_src

copy from [[https://codewithandrea.com/articles/flutter-navigate-without-context-gorouter-riverpod/][How to Navigate Without Context with GoRouter and Riverpod in Flutter]]

** go_router_build does not work with router enum

#+begin_example
The issue is that the @TypedGoRoute annotation can't resolve
the RouterEnum values at compile time.
The annotation requires string literals, not enum values.
#+end_example