* lsp-bridge language server installation

** python3 requirement

*** linux

#+begin_src shell
sudo apt install python3-pip
pip3 install epc orjson sexpdata six setuptools paramiko rapidfuzz watchdog packaging
#+end_src

** macos

#+begin_src shell
pip3 install --break-system-packages --upgrade epc orjson sexpdata six setuptools paramiko rapidfuzz watchdog packaging

python3.12 -m pip install --break-system-packages --upgrade pip
#+end_src

copy from [[https://emacs-china.org/t/lsp-bridge/20786/2996][lsp-bridge – 速度最快的语法补全插件]]

** install on macos

*** python language server
#+begin_src shell
brew install pyright pyenv ruff-lsp

pip3 install --break-system-packages basedpyright
#+end_src

*** kotlin language server
#+begin_src shell
HOMEBREW_BOTTLE_DOMAIN= ALL_PROXY=socks5://127.0.0.1:10808  brew install kotlin-language-server
// or reinstall
HOMEBREW_BOTTLE_DOMAIN= ALL_PROXY=socks5://127.0.0.1:10808  brew reinstall kotlin-language-server
#+end_src

see [[https://n2n1.cn/article-785-1-1.htm][mac安装kafka运行错误@@HOMEBREW_JAVA@@/bin/java: No such file or directory]]
also see [[https://github.com/orgs/Homebrew/discussions/2530][brew bottle command replaces JAVA_HOME path with @@HOMEBREW_JAVA@@ #2530]]
这是因为brew只知道如何从 ghcr.io 获取清单, 但我们用了其他的源，导致找不到对应的文件。

**** compile kotlin language server from source

#+begin_src shell
git clone https://github.com/fwcd/kotlin-language-server
cd kotlin-language-server
./gradlew :server:installDist -PjavaVersion=17

export PATH=$PWD/server/build/install/server/bin:$PATH
#+end_src

*** misc language server
#+begin_src shell
brew install sql-language-server yaml-language-server
#+end_src

** lsp-bridge remote server

*** on the remote machine

#+begin_src shell
python3 ~/.emacs.d/var/straight/repos/lsp-bridge/lsp_bridge.py
#+end_src

*** open with tramp package

copy from [[https://github.com/manateelazycat/lsp-bridge][lsp-bridge]]

** lsp-bridge open remote project

#+begin_quote
1 macos ssh 连接到远程服务器，中途离开，关闭 emacs，然后回来又打开 emacs。但 ssh 没有断开，后台 ssh 一直都在连接着。
2 在 dashboard 打开 sshx 文件, lsp-bridge没有启动成功
3 切换到打开的文件，c-x c-j 打开 dired， 打开另外一个文件，跟上面的 sshx 文件不是同一个
   3.1 在这时就要输入 ssh 到远程服务器的密码了，然后 lsp-bridge 就启动正常了。
   3.2 最初那个sshx 打开的文件，关闭后重新打开，也正常了。
#+end_quote

** rust package open error

Sometimes, lsp-bridge does not open the rust package properly.
But it opens it with `lib.rs` file, and then open the other rust file, it will reconized properly.